### ISSUE TITLE
SoapClient not found

### ISSUE THREAD

**Issue by victorze** [giansalex/greenter-sample#1]
Hola @giansalex, creo que en el README.md se debería incluir como paso adicional activar la extensión php_soap.dll en el fichero php.ini. Prové con Xampp y Laragon y no tenian activada esa extensión por defecto.

**Comment by giansalex** [comment]
Gracias por la observación, ya había agregado requisito acerca de las extensiones usadas, pero me falto esta. 
Esta requisito ha sido aplicado en el commit [#d2882ad](https://github.com/giansalex/greenter-ws/commit/d55449f1a4c7d33c4684a066038b0b24755a1f32)
