### ISSUE TITLE
ayuda

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#10]
ayudame amigo no puedo conseguir que este array se ingrese en los items
![captura](https://user-images.githubusercontent.com/34687414/35637585-a08905a4-0682-11e8-844a-f3ada7b31d9c.PNG)

**Comment by abelnexus** [comment]
trato de reemplazarlo por esto
![captura](https://user-images.githubusercontent.com/34687414/35637630-c75d5310-0682-11e8-8d36-5f36983b33fd.PNG)

**Comment by abelnexus** [comment]
lo cambie asi y si me genera el archivo xml y cdr de respuesta pero me bota un error siempre
![captura](https://user-images.githubusercontent.com/34687414/35638765-070488c8-0686-11e8-8a54-e2a9a83f2c3e.PNG)

**Comment by giansalex** [comment]
```php
$item = new SaleDetail();
$item->setUnidad($value['unidad'])
->setCantidad($value['cantidad'])
//...
$items[] = $item;
```

**Comment by giansalex** [comment]
cual es el error que te muestra.

**Comment by abelnexus** [comment]
ya no me manda el mensaje de confirmacion, si no que se cuelga ahi
![captura](https://user-images.githubusercontent.com/34687414/35646097-1384aa9a-069c-11e8-9161-e5c9e18c80d5.PNG)

**Comment by abelnexus** [comment]
creo saber de que se trata el error es por mi documento xml esta mal pero no me envia el mensaje de error por eso se cuelga

**Comment by giansalex** [comment]
las validaciones es un tema que también estoy desarrollando.

**Comment by abelnexus** [comment]
ya lo solucione, el error era que en mi bd la unidad de medida estaba como "niu" y solo acepta "NIU" en mayuscula al igual que "PEN"

**Comment by abelnexus** [comment]
aun asi hay errores que no entiendo, por ejejmplo al momento de crear al $invoice:
   ->setMtoOperGravadas(0)
    ->setMtoOperExoneradas(0)
    ->setMtoOperInafectas(0)
esos valores deben ser 0 por que en mi factura solo debe haber el total, el subtoal y el igv 
pero sunat me rechaza diciendo que no peude estar en cero :/

**Comment by giansalex** [comment]
pero tus facturas tienen igv, entonces debe haber Operaciones Gravadas, que es la suma del valor de venta de los items que tienen tipo de afectacion de IGV = 10

**Comment by abelnexus** [comment]
mmm eso no sabia, y los de "tipo afectacion igv = 10" = 

10,GRAVADO - OPERACION ONEROSA.
son solo para productos o servicios ?

**Comment by giansalex** [comment]
eso forma parte de temas de contabilidad, segun me informaron hay productos que son exonerados o inafectos a IGV, los servicios creo siempre son gravados con igv

**Comment by abelnexus** [comment]
entonces las gravadas  vienen a ser  el precio del producto - igv y la sumatoria de todos los items
mmmm ahora como saco eso de mi array D:

**Comment by abelnexus** [comment]
sunat es una m.. no se entiende sus explicaciones,
o se refiere al precio con el tu compraste el producto ? creo que ese es el valor de venta

**Comment by giansalex** [comment]
es que esos temas lo debe saber generalmente un contador.
Para obtener total gravados se suma el valor venta de cada ítem, el valor venta es `cantidad*precio unitario` (sin igv).

**Comment by abelnexus** [comment]
ahh ya te entendi entonces de esta venta mi operacion gravada es 293.8
![captura](https://user-images.githubusercontent.com/34687414/35684950-5e83b9b0-0736-11e8-9cc1-377d901a6d21.PNG)

**Comment by abelnexus** [comment]
gracias amigo no se donde estaria sin tu ayuda :)

**Comment by abelnexus** [comment]
ahhh no estoy mal esos mis precios ya tienen igv :'(

**Comment by abelnexus** [comment]
te refieres a ese que dice "valor unitario" verdad ?
![factura-spot](https://user-images.githubusercontent.com/34687414/35685837-c9de2a86-0738-11e8-871d-bcd1e62c011e.jpg)

**Comment by giansalex** [comment]
ese valor unitario vendría al precio sin igv, he estado pensando en crear un Github Pages, donde se puedan publicar estas cosas y que se pueda crear una guía para todos. También conertirlos manuales de sunat a paginas web y con la opcion que da github puedan editar o agregar cosas.

**Comment by abelnexus** [comment]
me agrada tu idea yo te apoyo, entonces si es la suma de "ese valor unitario"?

**Comment by giansalex** [comment]
seria la suma de ese valor unitario * cantidad

**Comment by abelnexus** [comment]
ya ahora si la tengo clara

**Comment by abelnexus** [comment]
gracias

**Comment by abelnexus** [comment]
una duda mas amigo quizás tengas alguna idea, tengo esta tabla y quisiera que en la columna estado se vea el estado del xml si ah sido aceptado o rechasado ya sea leendolo directamente desde el archivo xml o guardando la respuesta de sunat en la bd
![captura](https://user-images.githubusercontent.com/34687414/35688994-74637216-0740-11e8-899b-4276d4ddeff0.PNG)

**Comment by abelnexus** [comment]
creo que eso es mas complejo ya

**Comment by giansalex** [comment]
igual como muestras estado ABIERTA de la misma forma, cuando recibas la respuesta de SUNAT guardas el estado y descripcion

**Comment by abelnexus** [comment]
![captura](https://user-images.githubusercontent.com/34687414/35705522-a297475e-0770-11e8-82be-1ed03f61ba0c.PNG)

**Comment by abelnexus** [comment]
llegue a eso maximo uso este codigo:
<?php

require 'vendor/autoload.php';

$util = Util::getInstance();

$invoice = $util->getInvoice();

try {
    $pdf = $util->getPdf($invoice);
    $util->showPdf($pdf, $invoice->getName().'.pdf');
} catch (Exception $e) {
    var_dump($e);
}
?>

**Comment by abelnexus** [comment]
ahora si utilizo este codigo:
use Greenter\Model\Sale\Document;
use Greenter\Model\Sale\Invoice;
use Greenter\Model\Sale\SaleDetail;
use Greenter\Model\Sale\Legend;
use Greenter\Ws\Services\SunatEndpoints;
use Greenter\Model\Client\Client;
use Greenter\Model\Company\Company;
use Greenter\Model\Company\Address;

$client = new Client();
$client->setTipoDoc('6')
    ->setNumDoc('10486113532')
    ->setRznSocial('FERNANDO ABEL');
    // Emisor
$address = new Address();
$address->setUbigueo('150101')
    ->setDepartamento('LIMA')
    ->setProvincia('LIMA')
    ->setDistrito('LIMA')
    ->setUrbanizacion('NONE')
    ->setDireccion('AV LS');

$company = new Company();
$company->setRuc('20000000001')
    ->setRazonSocial('EMPRESA SAC')
    ->setNombreComercial('EMPRESA')
    ->setAddress($address);
// Venta
$invoice = new Invoice();
$invoice
    ->setFecVencimiento(new DateTime())
    ->setTipoDoc('01')
    ->setSerie('F001')
    ->setCorrelativo('000001')
    ->setFechaEmision(new DateTime())
    ->setTipoMoneda('PEN')
    ->setClient($client)
    ->setMtoOperGravadas(100)
    ->setMtoIGV(18)
    ->setMtoImpVenta(100)
    ->setCompany($company);

$item1 = new SaleDetail();
$item1
->setUnidad('NIU')                                             
->setCantidad(2)
->setDescripcion('LANA')
->setIgv(18)
->setTipAfeIgv('10')
->setMtoValorVenta(82)
->setMtoValorUnitario(100)
->setMtoPrecioUnitario(100);

$legend = new Legend();
$legend->setCode('1000')
    ->setValue('SON CIEN CON 00/100 SOLES');

$invoice->setDetails($item1)
    ->setLegends([$legend]);

try {
    $pdf = Util::getPdf($invoice);
    Util::showPdf($pdf, $invoice->getName().'.pdf');
} catch (Exception $e) {
    var_dump($e);
}

**Comment by abelnexus** [comment]
me bota este error :(

![captura](https://user-images.githubusercontent.com/34687414/35706385-8d46e672-0773-11e8-88d6-e95af2bb2547.PNG)

**Comment by giansalex** [comment]
tienes la ultima version del codigo?

**Comment by abelnexus** [comment]
si hoy mismo lo volvi a descargar

**Comment by giansalex** [comment]
el codigo que muestra a cambiado, ahora se hace asi.
```php
// $invoice = $util->getInvoice();

$util = Util::getInstance();

try {
    $pdf = $util->getPdf($invoice);
    $util->showPdf($pdf, $invoice->getName().'.pdf');
} catch (Exception $e) {
    var_dump($e);
}
```
tambien elimina los archivos de cache

**Comment by abelnexus** [comment]
sigue el mismo error, parece que es alguna interferencia con mi controlador o mi framework por que si lo habro directamente si genera el pdf
![captura](https://user-images.githubusercontent.com/34687414/35708509-84cb939a-077c-11e8-9c09-f43ba3ae737f.PNG)

**Comment by abelnexus** [comment]
pero el detalle es que no puede estar afuera ya que tiene que el reporte tiene que ser dinamico

**Comment by giansalex** [comment]
y en que parte intentas mostar el PDF, deberia estar tal vez en un iframe

**Comment by abelnexus** [comment]
bueno te explico detalladamente quizas me das otra solucion

**Comment by abelnexus** [comment]
en esa pagina frmventas hay un diseño que te muestra algo para imprimir (trato de mostrar el reporte pdf en vez de ese diseño para imprimir)
![captura](https://user-images.githubusercontent.com/34687414/35708925-6158ceb2-077e-11e8-932c-7476f99b77bd.PNG)

**Comment by abelnexus** [comment]
con ese codigo javascript habro el frmventas y envio el codigo de la venta para obtener los datos 
![captura](https://user-images.githubusercontent.com/34687414/35708992-b2181e3e-077e-11e8-9772-af8c6e7f868f.PNG)

**Comment by abelnexus** [comment]
al darle click sobre eso me habre esta ventana con los datos de esa factura
![captura](https://user-images.githubusercontent.com/34687414/35709064-ebf821c6-077e-11e8-8626-85d64a9ad6e7.PNG)

**Comment by abelnexus** [comment]
estaba pensando quizas darle ahi mismo la apariencia de la factura yde ahi luego imprimirlo o  bien convertilo en pdf directamente con la funcion de goolge chrome , pero el detalle es que como hare para lo del codigo qr no tengo ni la ams minima idea de como se genera eso

**Comment by abelnexus** [comment]
ahora si reemplazo ese codigo del frmventas por el codigo que hay en example/report/factura.php
me sale esto :/
![captura](https://user-images.githubusercontent.com/34687414/35709330-fb0e3c30-077f-11e8-9947-35769a7d9d0c.PNG)

**Comment by abelnexus** [comment]
y al darle imprimir cuando es una ventana modal me da esta opcion es un pop-up creo
![captura](https://user-images.githubusercontent.com/34687414/35709685-abe8f68e-0781-11e8-92d9-980e343405d5.PNG)

**Comment by giansalex** [comment]
EL problema debe ser que los estas mostrando como si fuera un HTML y no lo es, para abrirlo en una ventana puedes usarse
`window.open("data:application/pdf," + escape(pdfString)); `

**Comment by abelnexus** [comment]
y ese codigo donde lo aplicaria?

**Comment by giansalex** [comment]
cuando recibes la respuesta del PDF, reemplazarla en la linea donde lanzas la ventana y actualmente te sale todo esos garabatos

**Comment by abelnexus** [comment]
lo coloque asi pero sigue botando esos garabatos
![captura](https://user-images.githubusercontent.com/34687414/35710056-5fc6380a-0783-11e8-810a-7847419ca90e.PNG)

**Comment by giansalex** [comment]
el problema es que ya no debes llamar $util->showPdf(),
pdfString no existe esa variable, tiene que ser $pdf.
```php
try{
$pdf = $utl->getPdf($invoice);
echo '<script>windows.open("data:application/pdf," + escape('.$pdf.'));</script>';
}
catch (Exception $e){
}
```

**Comment by abelnexus** [comment]
ahora no ocurre nada al darle click
![captura](https://user-images.githubusercontent.com/34687414/35735793-ee040e2e-07f3-11e8-89cd-07bba3f0f99e.PNG)

**Comment by abelnexus** [comment]
![captura](https://user-images.githubusercontent.com/34687414/35735809-fd626bd6-07f3-11e8-84dc-07ede5b0b230.PNG)

**Comment by giansalex** [comment]
he actualizado el script.
```php
try{
$pdf = $utl->getPdf($invoice);
echo '<script>window.open("data:application/pdf," + escape("'.$pdf.'"));</script>';
}
catch (Exception $e){
}
```

**Comment by abelnexus** [comment]
entonces vuelvo a descargar greenter-sample?

**Comment by giansalex** [comment]
solo es esta linea:
```php
echo '<script>window.open("data:application/pdf," + escape("'.$pdf.'"));</script>';
```

**Comment by abelnexus** [comment]
nada :(

**Comment by abelnexus** [comment]
nada :(

**Comment by abelnexus** [comment]
amigo si solo quiero guardar el archivo pdf  y no abrirlo como seria el codigo

**Comment by abelnexus** [comment]
utilizo ese codigo y me genera el xml y el cdr pero no el pdf
$util = Util::getInstance();
           // Envio a SUNAT.
          $see = $util->getSee(SunatEndpoints::FE_BETA);
          $res = $see->send($data);
           Util::writeXml($data, $see->getFactory()->getLastXml());

          if ($res->isSuccess()) {
          /**@var $res \Greenter\Model\Response\BillResult*/
         $cdr = $res->getCdrResponse();
         Util::writeCdr($data, $res->getCdrZip());
         $this->sms = $util->getResponseFromCdr($cdr);  

         Util::writePdf($data, $pdf->getName().'.pdf');  
                              
         } else {
         $this->sms = $res->getError();
         }
		return $this->sms;

**Comment by giansalex** [comment]
en la linea  ` Util::writePdf($data, $pdf->getName().'.pdf'); ` , la variable $pdf no existe alli debe ir el nombre del PDF

**Comment by abelnexus** [comment]
en ese caso seria
util::writePdf($data, $data->getName().'.pdf'); 
pero igual no funciona

**Comment by abelnexus** [comment]
si lo utilizo asi si me crea el pdf, xml y cdr pero no me bota el mensaje ($this->sms)
$util = Util::getInstance();
           // Envio a SUNAT.
          $see = $util->getSee(SunatEndpoints::FE_BETA);
          $res = $see->send($data);
           Util::writeXml($data, $see->getFactory()->getLastXml());

          if ($res->isSuccess()) {
          /**@var $res \Greenter\Model\Response\BillResult*/
         $cdr = $res->getCdrResponse();
         Util::writeCdr($data, $res->getCdrZip());
         $this->sms = $util->getResponseFromCdr($cdr);
         $pdf = $util->getPdf($data);    
         $util->showPdf($pdf, $data->getName().'.pdf');                                                    
         } else {
         $this->sms = $res->getError();
         }
		return $this->sms;

**Comment by abelnexus** [comment]
amigo ya puedo guardar el pdf sin que me bote error, lo consegui eliminado de la clase
util - showpdf- echo content.
ahora me crea el xml el cdr y el pdf. 
alguna manera de abrir ese pdf ya creado ? me refiero a un evento que me habra el archivo recien creado

**Comment by giansalex** [comment]
para mostrarlo en el navegador, seria cuestión que abras el link del pdf generado en el servidor. en otra pestaña, o en un modal con iframe

**Comment by abelnexus** [comment]
ya lo consegui amigo me habre el pdf generado con este codigo
<?php foreach ($this->ventas as $clave => $valor) {?>
                    <tr>
                        <td class="text-center"><?=$valor['codigo']?></td>
                        <td class="text-center"><?=$valor['fecha']?></td>
                        <td class="text-center"><?=$valor['tipo_doc']?></td>
                        <td class="text-center">
                          <a href="../files/20491037785-01-<?=$valor['serie']?>-<?=$valor['numeracion']?>.pdf" target='_blank'>
                              <?=$valor['serie']?> - <?=$valor['numeracion']?>
                            </a>
                        </td>
                        <td><?=$valor['cliente']?></td>
                                       <td>

**Comment by abelnexus** [comment]
de alguna manera funciona pero siento que mi codigo esta muy mal :´( no es como quisiera siento que en cualqier momento puede fallar algo

**Comment by giansalex** [comment]
Si parte de ese orden y escalabilidad te lo provee los framework que se basan en algun patrón de diseño y arquitectura, entre ellos mi favorito es Symfony, para REST API uso SlimFramework

**Comment by abelnexus** [comment]
y con alguno de ellos ya aplciaste las librerias greenter ? cual me recomendarias para volver a hacer desde cero

**Comment by abelnexus** [comment]
el detalle es que tiene que ser dinamico y eso me complica un poco ya que mi conocimiento es limitado

**Comment by giansalex** [comment]
Con cualquiera se puede usar, pero aun no lo he realizado, aunque pretendo usar Symfony.
