### ISSUE TITLE
dudas y consultas

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#13]
hola amigo tengo algunas dudas que quisiera me ayudaras:
primero en nota_credito ese esta variable
 ->setCodMotivo('07')

se refiere a esto?
![captura](https://user-images.githubusercontent.com/34687414/36033283-91f3319c-0d7e-11e8-87dd-71213d7a6a0d.PNG)

**Comment by abelnexus** [comment]
el otro seria en $legend
$legend = new Legend();
$legend->setCode('1000')
    ->setValue('SON CIEN CON 00/100 SOLES');

ese setcode(1000) es determinado ?

**Comment by abelnexus** [comment]
el otro seria si quiero ser emisor electronico escuche que sunat te pide el certificado digital y su clave
pero el certificado que usamos con extension .pem no requiere clave como se hace en ese caso y que y como solicito a sunat para ser emisor

**Comment by abelnexus** [comment]
otro seria en el codigo qr de la representacion impresa debe ir ese contendio? cuando lo escaneo me bota los atributos de la factura como en un texto plano. y tambien escuche que se debe enviar a su correo del cliente la representacion impresa

**Comment by giansalex** [comment]
- El código Motivo es el Tipo de Nota (varia segun Nota de Crédito o Débito) el que muestras es para NCR
- Para la legenda con codigo 1000 son del [catalog 15](http://contenido.app.sunat.gob.pe/insc/Libros+y+Registros+Electronicos/Anexos+RS+199_2014/Nuevo+Anexo+8+-+Cat%C3%A1logos.pdf)
- El certificado se adquiere de un proveedor el te da la certificado.pfx y la clave, esto luego lo conviertes e .PEM 
- Acerca del codigo QR va informacion de la venta, eso se especifica en la ultima hoja de [manual de aspectos tecnicos](http://www.sunat.gob.pe/legislacion/superin/2015/anexoC-357-2015.pdf)

**Comment by abelnexus** [comment]
entonces el codigo motivo solo es '07' y '08 ?'

**Comment by abelnexus** [comment]
->setTipoDoc('07') este si se que es 07 por que es nota_credito
->setCodMotivo('07')  estaba seguro que era ese cuadro que te meustro arriba

**Comment by giansalex** [comment]
el código motivo puede ser de 2 listas, para NCR es del catalogo 9 y para NDB es del catalogo 10

**Comment by abelnexus** [comment]
amigo como saco el status o descripcion de un xml ya creado (la factura nro f001-000001 ha sido aceptada) y mostrarlo con un echo

**Comment by giansalex** [comment]
Esa respuesta se obtiene del xml de respuesta que te devuelve sunat (dentro de zip - CDR), para ello puedes usar 
```php
$path = __DIR__ . 'R-20600995805-01-F001-1.xml';
$xml = file_get_contents($path);
$reader = new DomCdrReaderInterface();
$cdr = $reader->getCdrResponse($xml);

echo $cdr->getDescription();
```
DomCdrReaderInterface forma parte de `greenter/ws` el cual ya esta incluido en `greenter`

**Comment by abelnexus** [comment]
stoy usando estas clases 
use Greenter\Model\DocumentInterface;
use Greenter\Model\Response\CdrResponse;
 y no me reconoce el 'DomCdrReaderInterface'

**Comment by giansalex** [comment]
Disculpa el namespace es este:
```php
use Greenter\Ws\Reader\DomCdrReaderInterface;
```

**Comment by abelnexus** [comment]
no entiendo que esta mal este es el codigo
     <?php
include '../vendor/autoload.php';

use Greenter\Ws\Reader\DomCdrReaderInterface;

$path = __DIR__.'../files/R-20491037785-01-F001-000112.xml';
$xml = file_get_contents($path);
$reader = new DomCdrReaderInterface();
$cdr = $reader->getCdrResponse($xml);

echo $cdr->getDescription();
?>

**Comment by abelnexus** [comment]
y este el error
![captura](https://user-images.githubusercontent.com/34687414/36064478-8f5a00ba-0e59-11e8-84d7-678520e8602f.PNG)

**Comment by abelnexus** [comment]
y este el archivo que quiero abrir
![captura](https://user-images.githubusercontent.com/34687414/36064488-a82275d2-0e59-11e8-80f6-e59caa005115.PNG)

**Comment by giansalex** [comment]
el codigo que te mostre es explicitamente para obtenerlo de un XML no de ZIP, el codigo completo seria este.
```php
use Greenter\Ws\Reader\DomCdrReaderInterface;
use Greenter\Zip\ZipHelper;


$path = DIR.'../files/R-20491037785-01-F001-000112.zip';
$zip  = file_get_contents($path);
$helper = new ZipHelper();
$xml = $helper->decompressXmlFile($zip);

$reader = new DomCdrReaderInterface();
$cdr = $reader->getCdrResponse($xml);

echo $cdr->getDescription();
```

**Comment by abelnexus** [comment]
ya salio gracias papi :D

**Comment by abelnexus** [comment]
D: amigo como evito que me muestre el mensaje de error
![captura](https://user-images.githubusercontent.com/34687414/36064755-96b6e568-0e5d-11e8-9e80-9763e64a78fa.PNG)

**Comment by abelnexus** [comment]
<?php
                          
$path = 'files/R-20491037785-01-'.$valor['serie'].'-'.$valor['numeracion'].'.zip';
if(isset($path)){
$zip  = file_get_contents($path);
$helper = new ZipHelper();
$xml = $helper->decompressXmlFile($zip);

$reader = new DomCdrReaderInterface();
$cdr = $reader->getCdrResponse($xml);

echo $cdr->getDescription();
}
else{
    echo 'no existe respeusta';
}

?>

**Comment by abelnexus** [comment]
ya lo solucione amigo:
                        <?php
                          
$path = 'files/R-20491037785-01-'.$valor['serie'].'-'.$valor['numeracion'].'.zip';
if(file_exists($path)){
$zip  = file_get_contents($path);
$helper = new ZipHelper();
$xml = $helper->decompressXmlFile($zip);

$reader = new DomCdrReaderInterface();
$cdr = $reader->getCdrResponse($xml);

echo $cdr->getDescription();
}
else{
    echo 'no existe respeusta';
}

?>

**Comment by abelnexus** [comment]
ahora si bien me muestra que se envio se puede saber si tiene errores o falta enviar ?

**Comment by abelnexus** [comment]
pero eso tendria que ir directo al xml verdad ?

**Comment by giansalex** [comment]
esa información de estados debes alojarla en la base de datos, cuando envias recibes la respuesta, si fue aceptada, tiene errores o es rechazada. De alli actualizas el estado de la venta.

**Comment by abelnexus** [comment]
si pensaba hacer eso pero al momento de recibir el error 
solo me mustra objet objet nada mas:
$this->sms = $util->getResponseFromCdr($cdr);                                   
         } else {
         $this->sms = $res->getError();

**Comment by giansalex** [comment]
es que ambos te devuelven un object, en el primero debes obtener ` $util->getResponseFromCdr($cdr)->getDescription();` y del error `$res->getError()->getMessage();`

**Comment by abelnexus** [comment]
:o amigo donde aprendiste a programar o como sabes tanto, que debo leer para saber estas cosas

**Comment by giansalex** [comment]
>  Lo normal - de libros, cursos, tutoriales.     

Tambien es bueno usar un buen IDE, por ejemplo para php uso PhpStorm de esa forma no tienes que buscar documentación, los metodos hablan por si solos. Y ya que `greenter` no tiene un documentación general  aun, esto es una buena ayuda.
![image](https://user-images.githubusercontent.com/14926587/36065001-235ad08e-0e62-11e8-8082-63bf119ca07d.png)

Ya puse la primer piedra para la documentación en esta pagina https://giansalex.github.io/greenter/

**Comment by abelnexus** [comment]
seguir estudiando duro entoces :D gracias

**Comment by abelnexus** [comment]
hola amigo una duda para las facturas que son mayores de 700 tiene que haber detracción o retencion creo es eso se debe programar tambien al momento de crear la factura ?

**Comment by giansalex** [comment]
la detracción se aplica cuando tiene servicios, la retención depende si la empresa es agente de retención.

**Comment by abelnexus** [comment]
de lo que estoy haciendo es prestacion de servicios  como aplico esa detraccion en mi factura (solo si es mayor de 700 el monto) debo sacarle el mondot de detraccion o solo envio el monto total y sunat ya ve que hace ?

**Comment by giansalex** [comment]
hay un campo para la detraccion.
`
$invoice = new Invoice();
$invoice->setDetraccion((new Detraction())
    ->setMount(2228.3)
    ->setPercent(9)
);
`

**Comment by abelnexus** [comment]
hola amigo las notas de debito y credito son para facturas y boletas ?

**Comment by abelnexus** [comment]
que es 'Nro.R.I. Emisor: 212321' ?
'

**Comment by giansalex** [comment]
Es la resolución de Sunat que te autoriza como Emisor Electronico

**Comment by abelnexus** [comment]
amigo como hago para que windows.open(url) funcione despues de 5 seg ?

**Comment by giansalex** [comment]
```js
setTimeout(function(){ 
windows.open(url);
}, 5000); // 5000 ms
```

**Comment by abelnexus** [comment]
hola amigo gracias funcione en window.open
ahora tengo un problema mayorrrrr: ya resulta que si puedo abrir el pdf pero no es dinamico

**Comment by abelnexus** [comment]
tengo este codigo 
$(".frm-ventas").submit(function(event) {
        event.preventDefault();
        var url = $(this).attr('action');
        var data = $(this).serialize();
        $.ajax({
            type:'POST',
            dataType:'json',
            url:url,
            data:data,
            success:function(response){
                $('#caja').toggle();
                $("span").remove( ".mensaje" );
                $("i").remove('.glyphicon');
                $("#caja").fadeOut(5000);

                if (response.respuesta == true) {
                    $(".box-pago").hide();
                   setTimeout(function(){ 
                  window.open("examples/report/factura.php");
                   }, 5000); // 5000 ms                  
                    $('#caja').removeClass('alert-danger').addClass('alert-info');
                    $("#caja").append("<i class='glyphicon glyphicon-info-sign' aria-hidden='true'></i>");
                    $("#caja").append("<span class='mensaje'>"+" RESPUESTA SUNAT: "+response.mensaje+"</span>");
                    $('.cargando').toggle();
                    $('.cargando p').html('Limpiando el carrito...');
                    setTimeout(llenar_tabla_json, 2000);
                    limpiarformulario($(".frm-ventas"));
                    
                }else{
                    $('#caja').removeClass('alert-info').addClass('alert-danger');
                    $("#caja").append("<i class='glyphicon glyphicon-exclamation-sign' aria-hidden='true'></i>");
                    $("#caja").append("<span class='mensaje'>"+" Error: "+response.mensaje+"</span>");
                }
            },error:function(){
                alert("Ha ocurrido un error");
            }
        });
    });

**Comment by abelnexus** [comment]
captura el momento de enviar el submit y me bota el mensaje de confirmacion y eso ahora
 $invoice->setDetails($items)
                                  ->setLegends([$legend]);

                            $mensaje = $this->model->generar_factura($invoice);
                            $mensajeError = $mensaje;

alguna manera de enviar esa variable $invoice mediante el codigo de arriba y asi sea dinamico el pdf ?

**Comment by abelnexus** [comment]
Fatal error: Uncaught TypeError: Argument 1 passed to Util::getPdf() must be an instance of Greenter\Model\DocumentInterface, string given, called in C:\xampp\htdocs\invoice\examples\report\factura.php on line 9 and defined in C:\xampp\htdocs\invoice\src\Util.php:74 Stack trace: #0 C:\xampp\htdocs\invoice\examples\report\factura.php(9): Util->getPdf('[object Object]') #1 {main} thrown in C:\xampp\htdocs\invoice\src\Util.php on line 74

**Comment by giansalex** [comment]
Segun el error estas pasando un string en vez de un object (Invoice por ejemplo)

**Comment by abelnexus** [comment]
este codigoe stoy usando amigo 

<?php

require __DIR__ . '/../../vendor/autoload.php';

$data = $_GET['invoice'];
  $util = Util::getInstance();
       
        $pdf = $util->getPdf($data);
        $util->showPdf($pdf, $data->getName().'.pdf');
?>

**Comment by abelnexus** [comment]
y este es la url 
localhost:82/invoice/examples/report/factura.php?invoice=[object%20Object]

**Comment by giansalex** [comment]
de donde obtienes `$data `, en la url envias `invoice=[object%20Object]`, ese valor no debe ser valido, que valor pretendes enviar en invoice.

**Comment by abelnexus** [comment]
$data es la variable que captura por get  la variable invoice que envie desde ajax

**Comment by giansalex** [comment]
para enviar objetos complejos deberias enviarlos por POST

**Comment by abelnexus** [comment]
lo envio de esta manera amigo:
$salidaJson=array('respuesta' => $mensajeOk,'mensaje' => $mensajeError, 'invoice' => $invoice);
			echo json_encode($salidaJson);

**Comment by abelnexus** [comment]
$(".frm-ventas").submit(function(event) {
        event.preventDefault();
        var url = $(this).attr('action');
        var data = $(this).serialize();
        $.ajax({
            type:'POST',
            dataType:'json',
            url:url,
            data:data,
            success:function(response){
                $('#caja').toggle();
                $("span").remove( ".mensaje" );
                $("i").remove('.glyphicon');
                $("#caja").fadeOut(6000);

                if (response.respuesta == true) {
                    $(".box-pago").hide();
                    imprimir_ticket(response.codigo);
                    $('#caja').removeClass('alert-danger').addClass('alert-info');
                    $("#caja").append("<i class='glyphicon glyphicon-info-sign' aria-hidden='true'></i>");
                    $("#caja").append("<span class='mensaje'>"+" Ok: "+response.mensaje+"</span>");
                    $('.cargando').toggle();
                    $('.cargando p').html('Limpiando el carrito...');
                    setTimeout(llenar_tabla_json, 2000);
                    limpiarformulario($(".frm-ventas"));
                }else{
                    $('#caja').removeClass('alert-info').addClass('alert-danger');
                    $("#caja").append("<i class='glyphicon glyphicon-exclamation-sign' aria-hidden='true'></i>");
                    $("#caja").append("<span class='mensaje'>"+" Error: "+response.mensaje+"</span>");
                }
            },error:function(){
                alert("Ha ocurrido un error");
            }
        });
    });

**Comment by giansalex** [comment]
en la primera parte es la respuesta que envias a la pagina, pero el anterior era cuando envias la informacion al servidor, alli es donde surge el problema

**Comment by abelnexus** [comment]
alguna diea de como se enviaria ese $invoice ?

**Comment by abelnexus** [comment]
$salidaJson=array('respuesta' => $mensajeOk,'mensaje' => $mensajeError, 'invoice' => $invoice);
echo json_encode($salidaJson);

en ese invoice lo tomo directamente de aca  
"$invoice"->setDetails($items)
                                  ->setLegends([$legend]);  y lo envio por el array

**Comment by abelnexus** [comment]
esta bien lo que estoy haciendo o no tiene sentido ?

**Comment by giansalex** [comment]
esto debe ser enviado por post:
`window.open("examples/report/factura.php?invoice="+response.invoice);`, al igual que hacer por ajax

**Comment by abelnexus** [comment]
amigo ayuda !!!
llegue hasta acá
	public function print_ticket()
	{
		
    if (isset($_POST['Codigo'])) {
		$data = array('CODIGO' => trim($_POST['Codigo']));		
		$util = Util::getInstance();
        $invoice = $util->getInvoice();
        try {
        $pdf = $util->getPdf($invoice);
        $util->showPdf($pdf, $invoice->getName().'.pdf');
        } catch (Exception $e) {
        var_dump($e);
        }
		}else{
			header("Location:".URL.'ventas');
		}
	}

esa variable Codigo es el $invoice como le aplico para que me cree dinamico (ya que me crea con el estatico)

**Comment by abelnexus** [comment]
probe reeemplazando el : 
$invoice = trim($_POST['Codigo']); y no crea el pdf

**Comment by giansalex** [comment]
código tiene el invoice, de que forma; es una cadena json? seria mejor si tienes el id de la venta, lo envias como parametro, luego consultas en la base de datos y armas el invoice.

**Comment by abelnexus** [comment]
entonces tendria que crear una bd para cada comprobante D:

**Comment by giansalex** [comment]
en donde almacenas el invoice, de allí puedes tomar la información segun los datos de la venta

**Comment by abelnexus** [comment]
el detalle es que no son iguales, boleta,factura != ntc  y ndb otros necesita mas datos que otro

**Comment by abelnexus** [comment]
como haria una cadena json ?

**Comment by giansalex** [comment]
y como generaste ese invoice, de la misma forma podrias volverlo hacer para generar el PDF, de esa forma no estas enviando información que ya esta disponible en el servidor. `getPdf($invoice)` recibe un DocumentInterface, el cual puede ser Invoice,Note, etc. podrias delegar ese trabajo en otra clase y que retorne el document object (invoice, note, ...) segun el tipo de venta (fac, bol, ncr, ndb) y se lo pasas a getPdf.

**Comment by abelnexus** [comment]
amigo ya logre solucionarlo funciona perfectamente siempre y cuando se envie y reciba el cdr :D mi reto sera ahora como hacer que reaccione el sistema en caso falle

**Comment by abelnexus** [comment]
quizas sepas amigo que: si en produccion envio un comprobante con el mismo numero de serie y numeracion me rechaza ?

**Comment by giansalex** [comment]
si, asi es. Te indica que el comprobante ya ha sido comunicado.

**Comment by abelnexus** [comment]
gracias amigo te pregunto esto por que estoy en duda si generar primero  la bd o primero el comprobante, ya que al generar la bd y no envia el xml o ocurre algun error estara grabada la serie y correlativo mas no el cdr y habra inconsistencia

**Comment by abelnexus** [comment]
asi que mejor al ocurrir un error hago que no se cree nada ni el pdf ni el xml ni el cdr y ya cuando se solcuione el error recien se cree, bueno por el momento sera asi ya que no me queda tiempo para estructurarlo mejor

**Comment by giansalex** [comment]
hay una serie de errores que pueden salir, muchas de ellas generan rechazo de la factura, y se tiene que volver a generar.  Para ello esta [greenter-validator](https://github.com/giansalex/greenter-validator), pero aun no están todas las validaciones listadas por SUNAT, ya que la lista es un poco larga.

**Comment by abelnexus** [comment]
si entiendo, me estan presionando y explotando creo. despues de entregar este sistema lo volvere a hacer muy bien estructurado

**Comment by abelnexus** [comment]
ayudame con esto amigo me esta dando problemas: quiero enviar este mensaje concatenado
$this->sms = "correcto".$util->getResponseFromCdr($cdr);
para hacerle la comparacion:
if($mensaje[0] == "correcto"){ 
    $mensajeOk = true;                        
     $mensajeError = $mensaje;

**Comment by abelnexus** [comment]
![captura](https://user-images.githubusercontent.com/34687414/36285574-1b7f3ae6-127a-11e8-9692-f292ef1c8a48.PNG)

**Comment by abelnexus** [comment]
mi intencion es que al recibir correcto me ingrese a la bd

**Comment by abelnexus** [comment]
no te molestes ya amigo, ya lo solucione :p

**Comment by giansalex** [comment]
ok, también toma en cuenta las notas del CDR, que vienen a ser las observaciones.

**Comment by abelnexus** [comment]
si eso me esta complicando y no se como manejarlo ya que mis items y todo estan en bd y para cambiar el precio o descuento o aumento y esas cosas se debe cambiar la bd misma y no hay usabilidad en ese aspecto :(

**Comment by giansalex** [comment]
Si, debe tener la posibilidad de edición.

**Comment by abelnexus** [comment]
amigo para el tema de envio de la representacion impresa  a los correos de los clientes ya lo viste ese tema? no tengo idea de eso

**Comment by giansalex** [comment]
Creo que esa la parte que falta para completar todo el proceso. El mas conocido para enviar mail es 
https://github.com/PHPMailer/PHPMailer sera el que use.

**Comment by abelnexus** [comment]
amigo vez algo que este mal en esta factura ?
![captura](https://user-images.githubusercontent.com/34687414/36328421-0354a332-1330-11e8-8e2c-58675c8de4a0.PNG)

**Comment by giansalex** [comment]
A que te refieres, al cálculo?  . cosas que se deberian cambiar
- la resolucion de Sunat,
- consulte en ....
- ~telf:~

**Comment by abelnexus** [comment]
mis operaciones gravadas esta correcto ? y tengo duda de la fecha de vencimiento

**Comment by abelnexus** [comment]
entonces quito la fecha de vencimiento. amigo recuerdas este codigo:
 if (codigo_documento == '07'|| codigo_documento == '08')
              {
              $("#note").show()

tengo problemas para validar que el campo no este vacio ya que cuando genero una factura no me crea por que en el documento de referencia (imput de la ndc) tengo puesto required

**Comment by abelnexus** [comment]
ya lo arregle amigaso :D

**Comment by abelnexus** [comment]
amigo en resumen diario de boletas:

        $detiail2 = new SummaryDetail();
        $detiail2->setTipoDoc('07')
            ->setSerieNro('B001-4')
            ->setDocReferencia((new Document())
                ->setTipoDoc('03')
                ->setNroDoc('0001-122'))
            ->setEstado('1')
            ->setClienteTipo('1')
            ->setClienteNro('00000000')
            ->setTotal(200)
            ->setMtoOperGravadas(40)
            ->setMtoOperExoneradas(30)
            ->setMtoOperInafectas(120)
            ->setMtoIGV(7.2)
            ->setMtoISC(2.8);

setdocreferencia a que  se refiere ? a que se ah dado de baja o se emitio una ndc o ndb ?

**Comment by abelnexus** [comment]
AMIGO LA SERIE DE NDB Y NDC SON iguales ? (FF01)

**Comment by giansalex** [comment]
la NCR y NDB depende del documento de referencia, si son para boletas es con BXXX,  para factura FXXX

**Comment by abelnexus** [comment]
me refiero a esto amigo 
![captura](https://user-images.githubusercontent.com/34687414/36562659-aa591a5a-17e5-11e8-8ff2-c530949ccfbd.PNG)
N0 FF01-XXXXXX DEBE SER IGUAL PARA NOTA DE DEBITO ?

**Comment by giansalex** [comment]
si es igual para ambos, si se relacionan a una factura(FXX) o boleta(BXXX)

**Comment by abelnexus** [comment]
diablos !!! eso me da un terrible error
la validación de mis datos no me deja guardar comprobantes con la misma serie y correlativo :(

**Comment by giansalex** [comment]
tienen que validarse junto con el tipo de documento, ya que las series son por tipo.
asi puede existir FAC F001-1 y NCR F001-1

**Comment by abelnexus** [comment]
buen día amigo, una consulta si una boleta fue enviada correctamente en que estado debe estar
![captura](https://user-images.githubusercontent.com/34687414/36598916-ace2f0c0-187b-11e8-9ea7-9fb3fed92918.PNG)

**Comment by abelnexus** [comment]
y sobre mi nota de credito estoy muy confundido:
si tengo esta serie y numeracion de mi nota de credito: F001-000001, B001-000002, F001-000003, B001-000004,B001-000005, EN MI NOTA DE CREDITO CAMBIA LA SERIE DE ACUERDO AL TIPO DE COMPROBANTE(SI ES BOLETA O FACTURA) PERO SE DEBE MANTENER EL CORRELATIVO(NUMERACION) ? O DEBE SER DIFERENTES NOTAS DE CREDITO PARA BOLETA Y FACTURA

**Comment by giansalex** [comment]
Las boletas no se envian individualmente (solo en servicio beta), en produccion se envia un resumen diario, en este caso el estado es `1-Adicionar` si vas anular `3-anulado`, 
> el `4` actualmente no es valido.

Las notas de credito y debito solo comparte el formato de la serie (FXXX O BXXX),  el correlativo es independiente para cada documento. ejm:
NCR FC01-1 emitidad a FAC F001-234
NCR B002-1 emitida a BOL BA01-3

**Comment by abelnexus** [comment]
entonces no me saldra errores si lo manejo asi :D ?
![captura](https://user-images.githubusercontent.com/34687414/36609156-f3f18aa8-1899-11e8-88a9-db1009873f10.PNG)

**Comment by giansalex** [comment]
no habra problema

**Comment by abelnexus** [comment]
entonces si solo se envia el resumen diario en la boleta no es necesario firmalo ni crear su xml si no almacernalo en una bd para luego enviarlo en un solo resumen diario

**Comment by abelnexus** [comment]
y en boletas solo tendria que ser dni y nro de documento? o en produccion te admite ruc, y se supone que las boletas no tiene igv :( que estresante es todo esto :'(

**Comment by giansalex** [comment]
tienes que generar el xml para el cliente,  si creo hay casos en los que se puede emitir boleta a un RUC, y por otro lado las boletas si tienen igv.
