### ISSUE TITLE
duda

### ISSUE THREAD

**Issue by guillermofoshlen** [giansalex/greenter-sample#14]
Buen dia, Esta excelente el soft que creastes
lo estado probando con xamp en mi laptop, uso windows 10 y corre de maravilla, pero cuando lo subo a mi hosting genera el xml, envia el xml, pero en el caso de generar el  pdf me sale error 
 en la clase util
 public static function getPathBin()
    {
        $path = __DIR__.'/../vendor/bin/wkhtmltopdf';
        if (self::isWindows()) {
            $path .= '.exe';
        }

        return $path;
    }
como podria cambiar para solucionar ese error, porfavor si me das una mano con este tema de generacion del pdf
muchas gracias por tu colaboracion, paciencia, y tiempo
![screenshot_2](https://user-images.githubusercontent.com/35127969/36240260-840c1904-11de-11e8-88c0-2a3c9af182cd.png)

**Comment by giansalex** [comment]
Si el problema es del path del binario de wkhtmltopdf, si usted puede instalar el software la linea de path queria asi.
```php
$path = 'wkhtmltopdf';
```
Otra opción, si puede ejecutar `composer install` , esto descargara el binario por usted negus el sistema operativo del Hosting. 
Si no puede ninguna de las opciones anteriores, descargarlo desde [wkhtmltopdf.org](https://wkhtmltopdf.org/downloads.html), subalo a su hosting al directorio `vendor/bin/`

**Comment by guillermofoshlen** [comment]
lo he usbido al hosting, pero no modifique nada en util.php
  public static function getPathBin()
    {
        $path = __DIR__.'/../vendor/bin/wkhtmltopdf';
        if (self::isWindows()) {
            $path .= '.exe';
        }

        return $path;
    }
deberia modificar algo hay, gracias por la ayuda y el tiempo brindado saludos
![screenshot_1](https://user-images.githubusercontent.com/35127969/36341286-eeb3d7c4-13b9-11e8-9dea-30e0d1b46fc0.png)

**Comment by giansalex** [comment]
Los hosting de PHP generalmente son linux, el ejecutable que estas subiendo es para windows, podría descargar la versión de 32bits para linux desde [aqui](https://raw.githubusercontent.com/h4cc/wkhtmltopdf-i386/master/bin/wkhtmltopdf-i386) , subirlo a la misma carpeta `vendord/bin/`  y darle permisos de ejecucion.
![image](https://user-images.githubusercontent.com/14926587/36342288-0e8bcace-13ca-11e8-8f5b-d9c808d6faa6.png)
