### ISSUE TITLE
Errores en Comunicacion de baja y Resumenes

### ISSUE THREAD

**Issue by wellynton1** [giansalex/greenter-sample#17]
Estimado, a que puede deberse el error cuando invoco a los documentos de Comunicación de Baja y Resúmenes:

En herokuapp:
"Ocurrío un error invocando el script
Time: 00:00:49:602"

El error también persiste en el localhost, estaba intentando comprender tus lineas pero algo falta en esos documentos:

Warning: Uncaught SoapFault exception: [HTTP] Error Fetching http headers in C:\xampp\htdocs\greenter-sample\vendor\greenter\ws\src\Ws\Services\SoapClient.php:61 Stack trace: #0 [internal function]: SoapClient->__doRequest('__soapCall('getStatus', Array) #2 C:\xampp\htdocs\greenter-sample\vendor\greenter\ws\src\Ws\Services\ExtService.php(33): Greenter\Ws\Services\SoapClient->call('getStatus', Array) #3 C:\xampp\htdocs\greenter-sample\vendor\greenter\greenter\src\Greenter\See.php(187): Greenter\Ws\Services\ExtService->getStatus('1528953679002') #4 C:\xampp\htdocs\greenter-sample\examples\comunicacion-baja.php(21): Greenter\See->getStatus('1528953679002') #5 {main} thrown in C:\xampp\htdocs\greenter-sample\vendor\greenter\ws\src\Ws\Services\SoapClient.php on line 61

Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\greenter-sample\vendor\greenter\ws\src\Ws\Services\ExtService.php on line 33
Time: 00:01:00:453

Gracias.

**Comment by giansalex** [comment]
Eso parece ser un error de PHP, por defecto el script no debe tomar mas de 30seg, puedes configurarlo en tu php.ini
http://php.net/manual/es/info.configuration.php#ini.max-execution-time

**Comment by carlossing** [comment]
cambia **max_execution_time** en php.ini

max_execution_time = 30

Cambia el 30 por algún otro valor mayor.

**Comment by wellynton1** [comment]
Muchas gracias por su colaboración, Exelente.
