### ISSUE TITLE
Tipo de Documento en Boletas

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#18]
hola amigo, queria preguntarte algo, cuando emito boletas de venta, puedo poner al cliente receptor con ruc "000000000" y razon social "publico en general"? es decir me rechaza eso en modo producción o me acepta

**Comment by giansalex** [comment]
un ruc tiene 11 digitos, dni 8, el numero que muestras tiene 9

**Comment by abelnexus** [comment]
perdon con dni de 8 ceros

**Comment by abelnexus** [comment]
me acepta ? por que tengo entendido que no es muy estricto en boletas

**Comment by giansalex** [comment]
si, segun las validaciones, para el caso de DNI, solo se validaria que tenga 8 digitos

**Comment by giansalex** [comment]
Las validaciones puedes encontrarlas en [la pagina de OSE](http://cpe.sunat.gob.pe/operador-de-servicios-electronicos-ose) en la sección **Archivo de Validación UBL 2.0 y 2.1**

**Comment by abelnexus** [comment]
genial muchas gracias amigo, para solo usar un receptor como publico general y ahorrar tiempo evitando ingresar sus datos
