### ISSUE TITLE
dar de baja un comprobante modificado

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#21]
hola amigo, cuando utilize una nota de credito o debito para modificar una factura, esta factura se puede dar de baja o ya no tiene valor por que se modifico y tendria que dar de baja la nota de credito o debito(que pasa si doy de baja esa factura que fue modificada)?

**Comment by giansalex** [comment]
Si ya lo modificaste aplicando la nota de crédito, no debieras darlo de baja, probablemente sunat lo rechazaría

**Comment by abelnexus** [comment]
gracias, quiero para validar eso capaz algún usuario lo da de baja sobre que ya lo modifico :D
