### ISSUE TITLE
¿Qué implica ese isSuccess?

### ISSUE THREAD

**Issue by thefantas** [giansalex/greenter-sample#22]
https://github.com/giansalex/greenter-sample/blob/dbedc0257f0dd2afc7786b12191ee7bce2962cb4/examples/factura.php#L72
Hola ese isSuccess valida solo el retorno de la consulta a la SUNAT en 0 (osea sin errores, acecptando el documento), supongo que también las observaciones error>3999, ya que también son XML aceptados por la sunat y te devuelven un CDR con aceptación con errores.

Saludos.

**Comment by giansalex** [comment]
Hola @thefantas , lo que hace es indicar si hubo una respuesta de Sunat, es decir que hubo CDR la cual independientemente si estuvo aceptada, rechazado o con observaciones.
