### ISSUE TITLE
Voided.php ¿Generación o Comunicación?

### ISSUE THREAD

**Issue by thefantas** [giansalex/greenter-sample#26]
```
    public function getName()
    {
        return $this->company->getRuc().'-'.$this->getXmlId();
    }

    /**
     * Get Id XML.
     *
     * @return string
     */
    public function getXmlId()
    {
        $parts = [
            'RA',
            $this->getFecComunicacion()->format('Ymd'),
            $this->getCorrelativo(),
        ];

        return join('-', $parts);
    }
```
Según el manual del programador SUNAT 2017 dice que la posición 16-23 del nombre del archivo enviado (y a la vez recibido R-) es el siguiente:

> Fecha de la generación del archivo en formato
> YYYYMMDD
Por lo que debería quedar así:
```
        $parts = [
            'RA',
            $this->setFecGeneracion()->format('Ymd'),
            $this->getCorrelativo(),
        ];
```

Y voided.php tiene dos fechas:

setFecGeneracion <-- Supuse que es la fecha en la que genera el documento de baja.
setFecComunicacion <-- La fecha del documento de baja (el día de la baja de los documentos).

¿Alguien puede aclarar qué significa setFecGeneracion y setFecComunicacion?
Saludos.

**Comment by giansalex** [comment]
Hola @thefantas , esto parece ser un poco confuso, había adoptado el modelo que usaba Sunat en su Facturador **(SFS)**, pero aqui esta la explicación.
- **setFecGeneracion:** Fecha del documento que se dará de baja.
> En el caso de facturas electrónicas previamente comunicadas a SUNAT, corresponderá
a aquella consignada como fecha de emisión.
Todos los documentos informados en una comunicación de baja deberán corresponder a
una misma fecha de generación.

- **setFecComunicacion:** Fecha en la cual se generó la Comunicación de baja.

Para mayor información, puedes ver la [guía de comunicación de baja](http://contenido.app.sunat.gob.pe/insc/ComprobantesDePago+Electronicos/Guias_manualesabr2013/Guia+XML+Comunicacion+de+Baja+revisado.pdf)

**Comment by thefantas** [comment]
Ok, gracias por la precisión, la documentación de SUNAT es muy contradictorio por donde se vea.

**Comment by thefantas** [comment]
He visto que has echo una modificación en (https://github.com/giansalex/greenter-xml/commit/b38833ef9336631487840afd2b8b975cf9fb5b44), esto de debe al cambio de concepto que harás?
Saludos.

**Comment by giansalex** [comment]
Si, forma parte, sera para una posterior versión.
