### ISSUE TITLE
como usar getStatusCdr - billConsultService

### ISSUE THREAD

**Issue by sysarp** [giansalex/greenter-sample#27]
Hola Ginacarlos,
Estoy tratando de implementar la funcion getStatusCdr y aun no logro que funcione con tus clases.

$USER = 'XXXXXXX';//RUC Y USUARIO SUNAT
$PASS='XXXXXXXX'//CONTRASENIA
$wsClient = new SoapClient('https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService?wsdl');
//$wsClient->setService('https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService');
$wsClient->setCredentials(USER,PASS);

$ExtService = new ExtService();
$ExtService->setClient($wsClient);
$cdr = $ExtService->getCdrStatus('20537897491','01','F001','1');

print_r($cdr->statusCdr);

y esto me devuelve error
Function ("setCredentials") is not a valid method for this service

ahora esto me funciona cuando envio el xml de ejemplo que indica sunat via la aplicacion SOAPUI

<soapenv:Envelope xmlns:ser="http://service.sunat.gob.pe" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
<soapenv:Header>
<wsse:Security>
<wsse:Username
Token>
<wsse:Username>XXXXXXXXXXXUSUARIO_SUNAT</wsse:Username>
<wsse:Password>XXXXXXXX</wsse:Password>
</wsse:UsernameToken>
</wsse:Security>
</soapenv:Header>
<soapenv:Body>
<ser:getStatus>
<rucComproba
nte>1028308796</rucComprobante>
<tipoComprobante>01</tipoComprobante>
<serieComprobante>f213</serieComprobante>
<numeroComprobante>12345</numeroComprobante>
</ser:getStatus>
</soapenv:Body>
</soapenv:Envelope>

**Comment by thefantas** [comment]
Yo pude hacerlo hace un mes creando una función en util.php
```
	//thefantas
    public function getConsulta($endpoint)
    {		
        $client = new SoapClient($endpoint . '?wsdl'); 
	$client->setCredentials(strtoupper('20000000000ABCDEFGH'), 'password');
        $client->setService($endpoint);
        $sunat = new ExtService();
		$sunat->setClient($client);
		return $sunat;
    }
```
$see_cdr = $util->getConsulta(SunatEndpoints::FE_CONSULTA_CDR);
$result = $see_cdr->getCdrStatus('20000000001', '01', 'F001', '2');
if ($result->isSuccess() && !empty($result->getCdrResponse())) {
 // procesa...
}

Y por último, ya que sunat da muchos errores y dolores de cabeza, modifiqué en ExtService.php

      ```
      $result->setCode($statusCdr->statusCode)
                ->setMessage($statusCdr->statusMessage)
		->setCdrZip(@$statusCdr->content)
                ->setSuccess(true);
            if (@$statusCdr->content)
                $result->setCdrResponse($this->extractResponse($statusCdr->content));
```

**Comment by sysarp** [comment]
Te agradesco por la informacion

**Comment by giansalex** [comment]
El problema debe ser porque estas usando el SoapClient nativo de PHP.
puedes importar el `namespace` o colocarlo explicitamente

```php
$wsClient = new Greenter\Ws\Services\SoapClient('https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService?wsdl');
```

**Comment by sysarp** [comment]
use Greenter\Ws\Services\ExtService;
use Greenter\Ws\Services\SoapClient;

EN UTIL

	public function getConsulta($ruc,$tipo,$serie,$numero){
		$endpoint = 'https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService';
		$wsClient = new SoapClient($endpoint . '?wsdl');
		$wsClient->setCredentials('xxxxxxxxxxxx','xxxxxxxxxx');
		$wsClient->setService($endpoint);

		$sunat = new ExtService();
		$sunat->setClient($wsClient);

		$rs = $sunat->getCdrStatus($ruc, $tipo, $serie, $numero);

		return $rs;
	}

DESDE ARCHIVO DONDE LLAMO LA FUNCION

		$cdr = new StatusCdrResult();
		$cdr = $util->getConsulta('XXXXXXXXXX','01','F001','1');
		if($cdr->isSuccess() && !empty($cdr->getCdrResponse())){
			print_r($cdr);
		}


RESPUESTA

<br />
<b>Warning</b>:  gzinflate(): data error in <b>AppServer/vendor/greenter/ws/src/Zip/ZipHelper.php</b> on line <b>203</b><br />
<br />
<b>Warning</b>:  DOMDocument::loadXML(): Empty string supplied as input in <b>AppServer/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php</b> on line <b>50</b><br />
<br />
<b>Notice</b>:  Trying to get property of non-object in <b>AppServer/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php</b> on line <b>52</b><br />
<br />
<b>Warning</b>:  DOMXPath::query(): Undefined namespace prefix in <b>AppServer/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php</b> on line <b>64</b><br />
<br />
<b>Warning</b>:  DOMXPath::query(): Invalid expression in <b>AppServer/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php</b> on line <b>64</b><br />
<br />
<b>Notice</b>:  Trying to get property of non-object in <b>AppServer/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php</b> on line <b>66</b><br />
{"Estado":"Error","Descripcion":"Not found cdr response in xml","FechaHora":"2018-09-10 10:09:06","data":[],"Registros":"0","Total":"0"}


NO FOUND CDR RESPONSE IN XML pero en la otra funcion si me devuelve el archivo, alguna sugerencia.

**Comment by giansalex** [comment]
Llegaste a probar [status-cdr.php](https://greenter-sample.herokuapp.com/examples/pages/status-cdr.php)?

**Comment by sysarp** [comment]
NOOOOOOOOOOOOOOOOOOOOOO, NO SABIA QUE YA LO TENIAN :(, queria ayudar con eso.

**Comment by sysarp** [comment]
Giancarlo status-cdr.php en el git.??

**Comment by giansalex** [comment]
Esta aqui
https://github.com/giansalex/greenter-sample/blob/master/examples/pages/status-cdr.php

**Comment by thefantas** [comment]
Haz la modificación en ExtService.php y el error desaparecerá.

**Comment by sysarp** [comment]
El que esta en esta ruta /vendor/greenter/ws/src/Ws/Services/ExtService.php

En la linea 77 

            /*	$result
                ->setCode($code)
                ->setSuccess(true);
			*/
			  $result->setCode($statusCdr->statusCode)
					->setMessage($statusCdr->statusMessage)
					->setCdrZip(@$statusCdr->content)
					->setSuccess(true);
			if(@$statusCdr->content)
				$result->setCdrResponse($this->extractResponse($statusCdr->content));

**Comment by sysarp** [comment]
Ya habia modificado la funcion pero igual me devuelve lo mismo:

public function getConsulta($ruc,$tipo,$serie,$numero){
	$endpoint = 'https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService';
	$wsClient = new SoapClient($endpoint . '?wsdl');
	$wsClient->setCredentials('xxxxxxxxxxxx','xxxxxxxxxx');
	$wsClient->setService($endpoint);

	$sunat = new ExtService();
	$sunat->setClient($wsClient);

	$rs = $sunat->getCdrStatus($ruc, $tipo, $serie, $numero);

	return $rs;
}

##
$cdr = new StatusCdrResult();
$cdr = $util->getConsulta('XXXXXXXXXX','01','F001','1');
if($cdr->isSuccess() && !empty($cdr->getCdrResponse())){
print_r($cdr);
}

########################################################################
## AHORA LO ESTOY PROBANDO DE ESTA FORMA Y LA RESPUESTA ES IGUAL / EL SETEO ES MANUAL.


<?php

use Greenter\Ws\Services\ExtService;
use Greenter\Ws\Services\SoapClient;
use Greenter\Ws\Services\SunatEndpoints;

require __DIR__ . '/../../../../vendor/autoload.php';

$errorMsg = null;

function validateFields(array $items){
	global $errorMsg;
	foreach ($items as $key => $value) {
		if (empty($value)) {
		    $errorMsg = 'El campo '.$key.', es requerido';
		    return false;
		}
	}
	return true;
}

function getCdrStatusService($user, $password){
	$ws = new SoapClient(SunatEndpoints::FE_CONSULTA_CDR.'?wsdl');
	$ws->setCredentials($user, $password);

	$service = new ExtService();
	$service->setClient($ws);

	return $service;
}

function process($fields){
/*
	if (!isset($fields['rucSol'])) {
		return null;
	}

	if (!validateFields($fields)) {
		return null;
	}
*/
	$service = getCdrStatusService('XXXXXXXXXX','XXXXXXXX');
	return $service->getCdrStatus('XXXXXXXXXX','01','F001','1');
}

function DocGetStatusCdr($args){
	try{

		$DOC = $args;
		$rsSunat = process([]);

		if($rsSunat->isSuccess()){

			$json = array();
			$json["Estado"] = "Cargado";
			$json['data']['rsCodigo'] = $rsSunat->getCode();
			$json['data']['rsDescripcion'] = '';
			return $json;
		}else{
			$error = $rsSunat->getError();
			throw new Exception("Error " . $error->getCode() . " | " .$error->getMessage());
		}
	}catch(Exception $e){
		$json = array();
		$json["Estado"] = "Error " . $e->getMessage();
		$json['data']['rsCodigo'] = '';
		$json['data']['rsDescripcion'] = '';
		return $json;
	}

}
?>


EL ERROR ES

<br />
<b>Warning</b>:  gzinflate(): data error in <b>/vendor/greenter/ws/src/Zip/ZipHelper.php</b> on line <b>203</b><br />
<br />
<b>Warning</b>:  DOMDocument::loadXML(): Empty string supplied as input in <b>/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php</b> on line <b>50</b><br />
<br />
<b>Notice</b>:  Trying to get property of non-object in <b>/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php</b> on line <b>52</b><br />
<br />
<b>Warning</b>:  DOMXPath::query(): Undefined namespace prefix in <b>/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php</b> on line <b>64</b><br />
<br />
<b>Warning</b>:  DOMXPath::query(): Invalid expression in <b>/AppServer/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php</b> on line <b>64</b><br />
<br />
<b>Notice</b>:  Trying to get property of non-object in <b>/vendor/greenter/ws/src/Ws/Reader/DomCdrReader.php</b> on line <b>66</b><br />
stdClass Object
(
    [rsCodigo] => 
    [rsDescripcion] => 
)


GRACIAS POR SUS RESPUESTAS

**Comment by giansalex** [comment]
![image](https://user-images.githubusercontent.com/14926587/45317540-e8c9ce80-b4ff-11e8-8c53-4d1490512c91.png)

**Comment by sysarp** [comment]
Sale este error con GREENTER-SAMPLE: 

 Fatal error: Uncaught Error: Class 'Greenter\Ws\Services\ConsultCdrService' not found in /greenter-sample/examples/pages/status-cdr.php:37 Stack trace: #0 /greenter-sample/examples/pages/status-cdr.php(61): getCdrStatusService('xxxxxxxxxxxx...', 'xxxxxxxxxxx') #1/greenter-sample/examples/pages/status-cdr.php(82): process(Array) #2 {main} thrown in /greenter-sample/examples/pages/status-cdr.php on line 37

**Comment by sysarp** [comment]
falto actualizar composer voy a revisarlo. gracias

**Comment by giansalex** [comment]
si, `git pull`, `composer update`

**Comment by sysarp** [comment]
GRACIAS!!!

use Greenter\Ws\Services\ConsultCdrService;
use Greenter\Ws\Services\SoapClient;
use Greenter\Ws\Services\SunatEndpoints;

$filename = null;

function savedFile($filename, $content)
{
    $pathZip = __DIR__.'/cache/'.$filename;
    file_put_contents($pathZip, $content);
}

function process($fields){
    global $filename;

    $ws = new SoapClient(SunatEndpoints::FE_CONSULTA_CDR.'?wsdl');
    $ws->setCredentials('XXXXXXXXXXXXXXXX','XXXXXXXXXXXXXXX');

    $service = new ConsultCdrService();
    $service->setClient($ws);

    $arguments = [
        $fields['rucComprobante'],
        $fields['tipoComprobante'],
        $fields['serieComprobante'],
        intval($fields['numeroComprobante'])
    ];

	if (isset($fields['cdr'])) {
		$result = $service->getStatusCdr(...$arguments);
		if ($result->getCdrZip()) {
		    $filename = 'R-'.implode('-', $arguments).'.zip';
		    savedFile($filename, $result->getCdrZip());
		}
		return $result;
	}
    return $service->getStatus(...$arguments);
}

function DocGetStatusCdr($args){
	try{
		$DOC = $args;
		$params = array(
			'cdr' => false,
			'rucComprobante' => 'xxxxxxxxxxxxxxxX',
			'rucComprobante' => $DOC['DocEmisorDocNumero'],
			'tipoComprobante' => $DOC['DocTipo'],
			'serieComprobante' => $DOC['DocSerie'],
			'numeroComprobante' => $DOC['DocNumero']
		);
		$rsSunat = process($params);

		if($rsSunat->isSuccess()){
			$json = array();
			$json["Estado"] = "Cargado";
			$json['data']['rsCodigo'] = $rsSunat->getCode();
			$json['data']['rsDescripcion'] = $rsSunat->getMessage();
			return $json;
		}else{
			$error = $rsSunat->getError();
			throw new Exception("Error " . $error->getCode() . " | " .$error->getMessage());
		}
	}catch(Exception $e){
		$json = array();
		$json["Estado"] = "Error";
		$json['data']['rsCodigo'] = $e->getCode();
		$json['data']['rsDescripcion'] = $e->getMessage();
		return $json;
	}
}

:)

**Comment by thefantas** [comment]
Que bien que hayas resuelto  tu problema, pero una consulta ¿Confías en el getStatus de FE_CONSULTA_CDR? porque desde haces unos días lo estoy probando y así  ponga un ticket inexistente o inválida me devuelve 0004La constancia existe.

Saludos.

**Comment by thefantas** [comment]
Deben corregir su código...
```
if (isset($fields['cdr'])) { <-- Solo comprueba que la variable esté definida, en su caso false o true da igual.
por...
if (isset($fields['cdr']) && $fields['cdr']) { <-- con esto además comprueba que sea true como me imagino que necesitan.
```

Saludos.

**Comment by giansalex** [comment]
Hola @thefantas , se usa esa comprobación porque son dos botones, uno para consultar el estado y el otro para obtener el CDR, el servicio **billConsultService** tiene 2 métodos `getStatus()` y `getStatusCdr`, validar que exista la variable (`isset($fields['cdr']`) me indica si fue el botón de _Consultar CDR_ o sino seria el otro, _Consultar Estado_

**Comment by thefantas** [comment]
Entonces que sea true o false es insignificante y poco práctico. ya que basta que esté definido ya procesa la condificional.

**Comment by giansalex** [comment]
Asi es solo comprueba que este definido, no importa el valor que tenga
