### ISSUE TITLE
Get CDR comunicación de Baja

### ISSUE THREAD

**Issue by thefantas** [giansalex/greenter-sample#28]
> 2.7.2  Para consulta de CDR en producción de Resumen Diario o
> Comunicación de Baja o Resumen de Reversiones o Lotes de Facturas.
> 
> getStatus (del ticket), este método recibe los datos de un ticket como
> parámetro y devuelve un objeto que indica el estado del proceso y en caso de
> haber terminado, **devuelve adjunto el CDR**. 

Según el manual del programador con el método getstatus()
```
$result = $see->getStatus($ticket);
print_r($result);
```
Debo obtener el CDR de la comunicación de baja, pero esto nunca ocurre, solo me devuelve "0004La constancia existe" (aún cuando tengo la certeza de que el documento ha sido aceptado).

¿Me estoy perdiendo de algo?
Saludos

**Comment by thefantas** [comment]
```
<?xml version='1.0' encoding='UTF-8'?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
<S:Body><ns0:getStatusResponse xmlns:ns0="http://service.sunat.gob.pe">
<status><statusCode>0004</statusCode>
<statusMessage>La constancia existe</statusMessage>
</status>
</ns0:getStatusResponse>
</S:Body></S:Envelope>
```
Es lo único que logro recepcionar, para que getCdrResponse() esté con datos la respuesta de la sunat debe tener content

```
            if ($code == '0' || $code == '99') {
                $result
                    ->setCdrResponse($this->extractResponse($cdrZip))
                    ->setCdrZip($cdrZip);
```
Pero como no es así, nunca veo el CDR del ticket. (no es CDR de factura es de comunicación de baja).

**Comment by giansalex** [comment]
Si lo que envías  es la respuesta de SUNAT, entonces no hay forma de obtener el CDR, ese es el mismo resultado que retorna el **getStatus** pero de https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService

**Comment by giansalex** [comment]
En la pagina de sunat hay una notificacion
http://www.sunat.gob.pe/mensajes/setiembre/2018/aviso-ti-100918.html

**Comment by thefantas** [comment]
No no, no envío el soap que mostré en la anterior respuesta, al contrario es lo que obtengo al consultar un ticket de RA, espero que sea problema de SUNAT como muestra el comunicado, seguiré probando.. en todo caso estoy en lo correcto o no?
Si tengo un ticket de una RA (comunicación de baja), luego puedo obtener el CDR con el método getStatus (según manual del programador) debería retornar el content con mi CDR, lo cual no ocurre.. asumo por problemas con la SUNAT.

**Comment by giansalex** [comment]
Me refería a que ese xml es la respuesta de sunat al consultar, y allí no se vee ningún campo content (CDR),
Si pruebas en QAS, veras el resultado esperado.

**Comment by thefantas** [comment]
Perdón QAS? qué significa?

**Comment by giansalex** [comment]
Me refereia BETA

**Comment by thefantas** [comment]
Me están diciendo que esto solo funciona en Beta y no producción? de ser así, no existe forma de obtener el CDR de una comunicación de baja con el ticket?

**Comment by thefantas** [comment]
Correción sí se puede, al parecer cometí un error endpoint, no se debe usar FE_CONSULTA_CDR sino FE_PRODUCCION para obtener el CDR con el ticket.

**Comment by giansalex** [comment]
Lo raro es que no reciben los mismos parametros, el servicio de CDR requiere datos de la factura (ruc, tipo., serie, correlativo), mientras que el de Servicio de Factura solo recibe el ticket del resumen o baja.

**Comment by thefantas** [comment]
Por eso yo quería el CDR de la baja (tenía el ticket) pero lo consultaba en FE_CONSULTA_CDR y solo me inidicaba que sí existe, mientras que en FE_PRODUCCION me devuelve el dichoso CDR.

**Comment by giansalex** [comment]
**FE_CONSULTA_CDR** se usa solo para consultar el estado y CDR de Factura y NCR, NDB asociadas. Si has revisado el manual del programador los tres métodos `sendBill`, `sendSummary`, `getStatus` estan disponibles en **FE_PRODUCCION**, pero puede ser confuso por que tambien esta el `getStatusCdr`.
Referente al cdr que obtuviste, el código es 133, el cual es <= 1999, según la documentación es una excepcion, tiene que volverse a enviar el documento, en este caso la comunicacion de baja.
> Del 0100 al 1999 Excepciones
 Del 2000 al 3999 Errores que generan rechazo
 Del 4000 en adelante Observaciones
