### ISSUE TITLE
consultas

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#3]
mi estimado vengo revisando tus librerias, y veo que envia directo a la sunat, hay alguna manera de guardarlo en formato xml y zip esas facturas ?

**Comment by giansalex** [comment]
Se agrego la opcion de guardar los xml y cdr en la carpeta `/data/`
commit [c7927dc](https://github.com/giansalex/greenter-sample/commit/c7927dc7c6dceae80cb307dd407f1194d12e720f)

**Comment by PercyWoeds** [comment]
Hola si quiero poner el numero de placa en una factura que campo es?
