### ISSUE TITLE
OffTopic: Error 2223 - El archivo ya fue presentado anteriormente

### ISSUE THREAD

**Issue by thefantas** [giansalex/greenter-sample#32]
Una consulta si de alguna manera perdí el ticket (ya sea por error del sistema o sunat) y cuando intento reenviar dice "2223 El archivo ya fue presentado anteriormente - El archivo ya fue presentado anteriormente" y al buscar dicho comprobante en la Sunat no existe.. ¿Qué medidas podría tomar?
Saludos.

**Comment by giansalex** [comment]
Es interesante esta pregunta, no me he topado con ese problema. Pero no he visto algún servicio para obtener el ticket o cdr de un resumen diario, aunque  `getstatusCdr`, debería servir para eso pero en su documentación indica que solo es para facturas (ncr, ndb).

**Comment by giansalex** [comment]
Al intentar consultar el `getStatusCdr()`, indica que el tipo de documento debe ser `01, 07, 08`.
Viendo que no hay servicio para eso, tendrias que ir al Portal de Sunat o a la pagina de [consulta validez](http://www.sunat.gob.pe/ol-ti-itconsvalicpe/ConsValiCpe.htm) para saber el estado del comprobante individual, sabiendo el de uno se podría generalizar para el resto de los comprobantes que conforman el resumen diario/comunicacion de baja.
