### ISSUE TITLE
Error: No tiene el perfil para enviar comprobantes electrónicos

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#35]
hola amigo, no se si solo a mi me ocurre, pero ya actualice a 2.1 y cuando le doy a enviar en modo producción otra vez me dice:
 Error: No tiene el perfil para enviar comprobantes electronicos - Detalle: Rejected by policy.
y ese error ya lo había corregido(no toque nada de las credenciales)

**Comment by giansalex** [comment]
Eso te ha ocurrido anteriormente?

**Comment by abelnexus** [comment]
si cuando use el usuario y contraseña pero sin ponerle primero el ruc me salia ese error, despues puse el ruc + usuario y ese error desaparecio, y aparecio el error  del ubl 2.1, ahora ya lo actualice y me vuelve a salir ese error

**Comment by abelnexus** [comment]
amigo ya solucione el error del perfil, ya envie una factura en produccion y lo di de baja, ahora consulte el comprobante y sigue apareciendo como valido, mi pregunta es tarda en dar de baja un comprobante o como consulto comprobantes dados de baja ?

**Comment by giansalex** [comment]
Podrías compartir cual fue el problema del  _error de perfil_.
Acerca de la comunicación de baja, obtuviste el CDR de respuesta?

**Comment by abelnexus** [comment]
el error no lo entiendo aun, pero lo que hice fue simple...
eliminar el usuario actual y crear uno nuevo, tuve que esperar 1 hora para que pueda usar el nuevo usuario y ya no me daba problemas.
si obtuve el crd de la comunicacion de baja y al consultar por aca: http://www.sunat.gob.pe/ol-ti-itconsvalicpe/ConsValiCpe.htm me indica que el comprobante es valido

**Comment by abelnexus** [comment]
ya esta solo era esperar un poco :D ya fue dado de baja

**Comment by giansalex** [comment]
Es algo a tener en cuenta, creare una sección en la pagina de greenter, de cosas a tener en cuenta.

**Comment by acsistemas** [comment]
> amigo ya solucione el error del perfil, ya envie una factura en produccion y lo di de baja, ahora consulte el comprobante y sigue apareciendo como valido, mi pregunta es tarda en dar de baja un comprobante o como consulto comprobantes dados de baja ? 

Hola estimado, una consulta, como fue que solucionaste este error? Error: No tiene el perfil para enviar comprobantes electrónicos a mi tambien me sale y no se como resolverlo, ya intentamos creando un usuario nuevo. Gracias

**Comment by giansalex** [comment]
Hola @acsistemas , tienes que esperar como al menos 24h, si has creado el usuario secundario con los permisos, tendrias que esperar.
> Tambien asegurate de haber puesto los datos de clave sol correctamente.

**Comment by acsistemas** [comment]
> Hola @acsistemas , tienes que esperar al menos 24h, si has creado el usuario secundario con los permisos, tendrias que esperar.
> 
> > Tambien asegurate de haber puesto los datos de clave sol correctamente.

Mil gracias... ya se soluciono, era que SUNAT aparentemente guardaba los cambios, insisti hasta 5 veces y finalmente guardo... y todo bien ahora. Gracias

**Comment by juanxodj** [comment]
A mi me sigue apareciendo este error... Desde el Lunes he activado 4 usuarios secundarios de 4 ruc diferentes y no me permite enviar. Ya le he asignado permisos, en confirmado email, he creado y vuelto a crear otros, etc y nada :/

**Comment by umiphos** [comment]
@juanxodj comunicate con la sunat directamente, por telefono atienden mas rapido, recuerda que hoy es el dia donde miles de usuarios tienen que facturar electronicamente, asi que deben estar saturados los servidores

**Comment by miandime** [comment]
A mi me sigue apareciendo este error, lo puse el usuario secundario con los permisaos y nada, luego puse el usuario normal, ya no el secundario e igual me sigue saliendo No tiene el perfil para enviar comprobantes electronicos

**Comment by giansalex** [comment]
Hola @miandime, verifica que estes enviando las credenciales correctamente.
```php
$see->setCredentials('20000000001MODDATOS'/*ruc+usuario*/, 'moddatos');
```

**Comment by miandime** [comment]
@giansalex en el beta si me funciona, la cosa es cuando pasa a producción lo he hecho con el usuario secundario y no funcionaba, entonces probe con el principal y nada, me sale el error No tiene el perfil para enviar comprobantes electronicos

**Comment by giansalex** [comment]
@miandime en beta no validan el usuario.
Y cargaste el certificado en portal de Sunat?

**Comment by miandime** [comment]
@giansalex si cargue el certificado en sunat

**Comment by miandime** [comment]
@giansalex tienes alguna forma de descargar el pdf?, porque me sale bien en la vista previa, pero como lo trato de descargar con dompdf, la imagen no sale

**Comment by giansalex** [comment]
@miandime ya pudiste conectar con el servicio de Sunat?

**Comment by AlexanderSaZa** [comment]
Buenos días, tengo el problema de envió de facturas a Sunat en modo producción, cual fue la solución

**Comment by IngGermanNina** [comment]
Buenas tardes a todos, les saluda german, también estoy teniendo el mismo problema **"No tiene el perfil para enviar comprobantes electrónicos", veo que algunos dicen que lo resolvieron otros dicen que aún le persiste el error.

Para estar alineados todos, los pasos son los siguientes (también ver imagenes):

1. crear usuario secundario en el portal web de la sunat
![image](https://user-images.githubusercontent.com/28762659/81993515-76ca5680-960b-11ea-8509-fda37006bcc3.png)

2. Darle los accesos de emisión de factura y boleta , al usuario secundario.
![image](https://user-images.githubusercontent.com/28762659/81993772-0bcd4f80-960c-11ea-8013-5b74bcc0455d.png)

3. con las credenciales del usuario secundario,  ingresar al portal web de la sunat y veras las opciones a las cuales tienes permisos (si lograste ingresar todo conforme, sino tendrás que seguir los pasos que la sunat te pida)
![image](https://user-images.githubusercontent.com/28762659/81994027-97df7700-960c-11ea-8fea-c91613fa3386.png)


NOTA:  A pesar que he seguido estos pasos, me sigue saliendo el mismo error  "no tiene el peril.......".
- ¿Me falta algo más que configurar en el portal web de la Sunat?.
-  Si los pasos que comento no es el correcto, ¿Alguien puede explicar cuales son?.
- Si los pasos que comento si son los correcto, ¿Alguien puede explicar un poco más al detalle como resolvió el error?

De ante mando, gracias a todos por su tiempo.

**Comment by giansalex** [comment]
Hola German, generalmente es esperar al menos 24h, o es lo que dice sunat.
Tambien algunos se han confundido al colocar el usuario en codigo:
Ejemplo de clave sol:
RUC: `20000000001`
USUARIO: `MODDATOS`
CONTRASEÑA: `modatos`

En el codigo debería colocarse las credenciales:
USUARIO: `20000000001MODDATOS`   (ruc + usuario sol)
CLAVE:  `modatos`

**Comment by IngGermanNina** [comment]
Ha pasado 24 horas y me volvió a salir el mismo mensaje de error "No tiene el perfil para enviar comprobantes electrónicos".

Yo soy el administrador de mi clave sol del portal de la SUNAT osea (el representante legal de mi pequeño negocio).

pero adicional, puse mis datos como usuario secundario.

- ¿que usuario va en el código? ¿el del representante legal o el del usuario secundario?
- ¿Hay conflictos si es la misma persona?

**Comment by giansalex** [comment]
No hay problema que sea tus mismo datos, el usuario que va en código es el usuario secundario, pero debido a estos inconvenientes podrías usar tu usuario principal de momento.

**Comment by IngGermanNina** [comment]
Gente buenas noches, les comento que ya pude solucionar el error No tiene el perfil para enviar comprobantes electrónicos",me contacte con la sunat por medio de su Chat en linea, adicional yo registré al usuario secundario desde el navegador Chrome, el usuario de la sunat  e dio estas instrucciones.
![image](https://user-images.githubusercontent.com/28762659/82389939-fd63a700-9a02-11ea-9dbe-de8048da6b48.png)
![image](https://user-images.githubusercontent.com/28762659/82389988-18361b80-9a03-11ea-9af8-045a85fe1902.png)

**Comment by giansalex** [comment]
> Gente buenas noches, les comento que ya pude solucionar el error No tiene el perfil para enviar comprobantes electrónicos",me contacte con la sunat por medio de su Chat en linea, adicional yo registré al usuario secundario desde el navegador Chrome, el usuario de la sunat e dio estas instrucciones.

Eso quiere decir que el problema era el navegador

**Comment by armflo** [comment]
> Gente buenas noches, les comento que ya pude solucionar el error No tiene el perfil para enviar comprobantes electrónicos",me contacte con la sunat por medio de su Chat en linea, adicional yo registré al usuario secundario desde el navegador Chrome, el usuario de la sunat e dio estas instrucciones.
> ![image](https://user-images.githubusercontent.com/28762659/82389939-fd63a700-9a02-11ea-9dbe-de8048da6b48.png)
> ![image](https://user-images.githubusercontent.com/28762659/82389988-18361b80-9a03-11ea-9af8-045a85fe1902.png)

muchas gracias amigo, seguí las indicaciones y pude solucionar el mismo inconveniente. GRACIAS
no fue necesario esperar 4 hrs, fue instantáneo

**Comment by hipogea** [comment]
Buenas tardes.

A mí me pasa algo extraño:
Creé una cuenta de usuario alternativo con los roles y permisos  adecuados, 
me sale el error : Usuario y contraseña  inválidos.  Esto no puede ser porque me he asegurado que  el usuario es RUC+username  y el password también, todo correcto

Luego para verificar, creé un segundo usuario ; con los mismos roles. Pero al intentarlo
me sale lo siguiente :  
Código:0111
Descripción:No tiene el perfil para enviar comprobantes electronicos -

Esto está para jalarse los pelos verdad?

**Comment by Dust1100010** [comment]
yo también he tenido este mismo error y apliqué las recomendaciones que indican pero no me funcionó, así que llamé a SUNAT y me indico que debo activar las opciones de SEE-Del Contribuyente y Envío de Documentos y con eso ya funciona después de unas 4 horas

**Comment by Dust1100010** [comment]
tienes que esperar unas 4 horas por lo menos

**Comment by Dust1100010** [comment]
tienes que esperar unas 4 horas por lo menos y trata de ingresar a sunat con las credenciales del usuario secundario para validar si esta con los permisos

**Comment by bryancorodova** [comment]
Si puedo entrar al usuario y aparecen las credenciales que le asigne pero igual sale ese error en el sistema de facturacion

**Comment by NathalyGil** [comment]
Buenos días, hace unos meses atrás tenía el problema y con usuario secundario se solucionó. Pero esta vez nuevamente tengo el mismo problema a pesar de hacer creado un nuevo usuario secundario, me funcionó bien un día y luego otra vez error. Alguién encontró otra forma de solucionarlo?

**Comment by Dust1100010** [comment]
A mi me esta pasando desde el lunes después de estar facturando 2 meses, según SUNAT es un intermitencia que estas teniendo con algunos  RUCs, esperemos que se solucione pronto

**Comment by NathalyGil** [comment]
> A mi me esta pasando desde el lunes después de estar facturando 2 meses, según SUNAT es un intermitencia que estas teniendo con algunos RUCs, esperemos que se solucione pronto

Exacto, yo vengo trabajando 06 meses y todo bien. Pero de un día a otro simplemente dejó de validar cdr. Una consulta te han dado fecha de resolución? De hecho creé un nuevo usuario secundario, esperé 04 horas y con este linkee las credenciales y me funcionó por 01 día, al día siguiente error nuevamente. Te han dado alguna solución el personal de SUNAT que te atendió o sólo es esperar?

**Comment by Dust1100010** [comment]
Es solo esperar, yo también estoy aplicando lo de tener varias cuentas facturadoras

**Comment by DannyHM0** [comment]
Al parecer hay un pequeño fallo en la estructura XML que proporciona la guia del programador de la SUNAT, en mi caso yo solo use la firma de Greenter, el envio lo estoy haciendo manualmente en PHP, en cuestion el error se encuentra en la siguiente linea xml


**estructura de la sunat**
` xmlns:wsse="http://docs.oasisopen.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" `
 
 **como deberia ser**
` xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"`
 
 Asi es, error clasico de solo un guion, a mi me funciono, tanto usando el servicio por POSTMAN, SOAP, .NET Y HOST
 _Espero a alguien le sirva esto_

**Comment by XdRonaldoxD** [comment]
Le cambie la estructura por como dijiste pero igual me sigue saliendo ese error  , del tema del perfil , alguien lo pudo solucionar ?

**Comment by NathalyGil** [comment]
Hola! Aquí en el 2025 con el mismo error de hace años pero a pesar de haber probado con varios usuarios secundarios sigue saliendo este error: 
Obtuvimos un error en la respuesta del OSE.

Mensaje original:
0111|No tiene el perfil para enviar comprobantes electronicos - Detalle: Rejected by policy.

Vengo batallando 5 días tratando de encontrar la solución pero sigue saliendo error. Alguien tiene el mismo problema y quizá lo haya solucionado diferente a cambiar las credenciales con usuario secundario?

**Comment by Dust1100010** [comment]
estas usando un proveedor intermediario?

**Comment by NathalyGil** [comment]
No, compré mi certificado digital, lo descargo, lo ingreso al Odoo y con las credencial de la sunat funciona. De hecho ha funcionado bien desde el 2023, algunas ocasiones intermitencias en la falla de recepción de comprobantes por SUNAT que los solucioné cambiando de usuario secundario. Pero ahora a pesar de ello, he tratado con 4 usuarios secundarios diferentes y aún así no permite validar comprobantes indicando el error 0111. 
Mi certificado aún no vence hasta junio2026, revisé que no se haya modificado nada de la configuración de SUNAT como carga del certificado digital o contraseñas de usuarios secundarios y nada. Cambio el usuario secundario, me permite validar uno o dos comprobantes en el odoo y al tercero nuevamente sale ese mensaje de error.

**Comment by Dust1100010** [comment]
yo tuve ese problema desde que comenté en el 2023, para el 2024 migre al proveedor ApiSunat.com y desde ahí no he tenido más ese problema, cobran 0.05 por cada documento y la verdad vale mucho la pena

**Comment by armflo** [comment]
El error Usuario y contraseña inválidos, creo que aparece cuando el usuario secundario tiene caracteres especiales

**Comment by GabrielAedoPozo** [comment]
buenas estoy buscando ayuda no se si era el repo indicado ya que estoy utilizando node. esto es lo que me sale: node server.js
◇ injected env (34) from .env // tip: ◈ secrets for agents [www.dotenvx.com]
◇ injected env (0) from .env // tip: ⌘ multiple files { path: ['.env.local', '.env'] }
ℹ️ Configuración SUNAT: ENV=prod, Endpoint=https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService?wsdl
◇ injected env (0) from .env // tip: ⌘ enable debugging { debug: true }
Verificando si la tabla productos ya tiene el seed completo...
Seed omitido: ya existen los 166 productos esperados con IDs del 1 al 166.
Servidor escuchando en http://localhost:3000
Verificando si la tabla productos ya tiene el seed completo...
Seed omitido: ya existen los 166 productos esperados con IDs del 1 al 166.
Total recibido (3) no coincide con total calculado (3.54). Se usará el calculado.
🔍 generarFacturaXML devolvió tipo: string
🔍 nombreArchivo (ZIP+XML): 20615816788-03-B001-00000061
🔍 SUNAT enviarASunat: ENV=prod, WSDL=D:\Dev\pos_system\backend\wsdl\billService.wsdl, existe=true
🔍 Endpoint operación: https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService
✅ Cliente SOAP creado correctamente
✅ Seguridad básica configurada
🔍 Enviando: { fileName: '20615816788-03-B001-00000061.zip', zipBase64Length: 3956 }
❌ Error completo en enviarASunat: {
  message: 'soap-env:Client.0111: No tiene el perfil para enviar comprobantes electronicos - Detalle: Rejected by policy.',
  code: undefined,
  response: undefined,
  body: undefined,
  faultcode: 'soap-env:Client.0111',
  faultstring: 'No tiene el perfil para enviar comprobantes electronicos - Detalle: Rejected by policy.',
  stack: 'Error: soap-env:Client.0111: No tiene el perfil para enviar comprobantes electronicos - Detalle: Rejected by policy.'
}
⚠️ Error en flujo SUNAT: soap-env:Client.0111: No tiene el perfil para enviar comprobantes electronicos - Detalle: Rejected by policy.
⚠️ Stack de error: Error: soap-env:Client.0111: No tiene el perfil para enviar comprobantes electronicos - Detalle: Rejected by policy.
    at finish (D:\Dev\pos_system\backend\node_modules\.pnpm\soap@1.9.1\node_modules\soap\lib\wsdl\index.js:525:35)
    at WSDL.xmlToObject (D:\Dev\pos_system\backend\node_modules\.pnpm\soap@1.9.1\node_modules\soap\lib\wsdl\index.js:501:16)
    at parseSync (D:\Dev\pos_system\backend\node_modules\.pnpm\soap@1.9.1\node_modules\soap\lib\client.js:314:33)
    at D:\Dev\pos_system\backend\node_modules\.pnpm\soap@1.9.1\node_modules\soap\lib\client.js:542:24
    at handleBody (D:\Dev\pos_system\backend\node_modules\.pnpm\soap@1.9.1\node_modules\soap\lib\http.js:229:17)
    at D:\Dev\pos_system\backend\node_modules\.pnpm\soap@1.9.1\node_modules\soap\lib\http.js:261:24
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)]

la verdad alguien me dijo que espere 24 horas. pero en un usuario anterior estuvo como 3 dias activo, cree otro para limpiar todo ustedes creen que si deberia esperar 24 horas y debe haber otra solucion?, perdon por utilizar esto para informarme, se que no es de greenter pero me ayudaria mucho si me aconsejaran
