### ISSUE TITLE
OSE en vigencia, greenter seguirá funcionando?

### ISSUE THREAD

**Issue by carlossing** [giansalex/greenter-sample#36]
Seguirá funcionando cuando se tenga que aplicar esto:

http://semanaeconomica.com/article/legal-y-politica/tributario/313496-sunat-nuevo-modelo-de-facturacion-electronica-sera-obligatorio-desde-el-2019/

**Comment by giansalex** [comment]
Hola @carlossing , cuando entren en vigencia las OSE, la librería seguirá funcionando, el principal cambio seria la ruta del servicio, que ya no seria de SUNAT sino del OSE que haya contratado.

**Comment by carlossing** [comment]
genial, felicitaciones por el trabajo hecho.
