### ISSUE TITLE
Consulta CDR

### ISSUE THREAD

**Issue by wellynton1** [giansalex/greenter-sample#38]
Estimado Gian
Me sale la siguiente pantalla al invocar "Consulta CDR", faltara instalar algo?

![image](https://user-images.githubusercontent.com/33947690/47129985-2d622b80-d25d-11e8-801e-841c24abb41f.png)

**Comment by giansalex** [comment]
Parece mas un problema relacionado al WebServer, pero de todos modos es difícil ayudarte sin ningún error que se muestre.
