### ISSUE TITLE
Consulta de Instalacion

### ISSUE THREAD

**Issue by jamesjhojam** [giansalex/greenter-sample#39]
Hola amigo, queria saber en que version de php esta desarrollado el proyecto, dado que lo probe en php 5.5 y 7.0 y en ninguna me corre

En php 5.5 me sale esto
Fatal error: Cannot use object of type DOMNodeList as array in C:\xampp\htdocs\factura\greenter-sample\vendor\greenter\ws\src\Ws\Reader\DomCdrReader.php on line 69
Time: 00:00:00:732

Y en php 7.0 en greenter-sample me sale esto
Ocurrío un error invocando el script
Time: 00:00:00:144

Gracias de antemano

**Comment by giansalex** [comment]
Hola @jamesjhojam , la version que debes utilizar es `>= 5.6`

**Comment by jamesjhojam** [comment]
Cambia la version de php del servidor a 7.0.27 porque solo tiene esa otra opcion y me sale esto

![imagen](https://user-images.githubusercontent.com/44175382/47232680-f5123880-d395-11e8-85ef-d6660abdaf23.png)

A que se debera amigo, me podrias dar una mano, gracias

**Comment by giansalex** [comment]
Puedes abrir la consola del navegador (`F12`), y ver que error arroja

**Comment by jamesjhojam** [comment]
Esto es lo que me sale en la consola

![imagen](https://user-images.githubusercontent.com/44175382/47246373-f1e17180-d3c2-11e8-9e73-e10be96743da.png)

A que de debera me podrias apoyar

**Comment by giansalex** [comment]
Tienes la extension `soap, xml, zip, openssl` instaladas.
También puedes habilitar la visualización de errores para PHP para poder ver el detalle

**Comment by InformaticoLlanero** [comment]
Me paso cuando no colocas en la consola:
composer run-script start --timeout=0

**Comment by giansalex** [comment]
@jamesjhojam , como te fué.
