### ISSUE TITLE
buen trabajo, te felicito eres un capo :D ,como seria para vizualizar esos xml en pdf 

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#4]

**Comment by giansalex** [comment]
Gracias, he desarrollado una pequeña ejemplo de reporte a Html y luego convertirlo a PDF - [greenter-report](https://github.com/giansalex/greenter-report), también se podría utilizar las diferentes librerías que hay en PHP para generar PDF por código, pero aun no hay ningún avance, ni alguien que contribuya.
![captura](https://user-images.githubusercontent.com/14926587/34628357-fa97a542-f231-11e7-9c36-8d40ac353e2a.PNG)

**Comment by giansalex** [comment]
se ha agregado la visualización del PDF en `greenter/sample `
