### ISSUE TITLE
atributos adicionales en el tag InvoiceTypeCode

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [giansalex/greenter-sample#41]
Una consulta @giansalex, el generador xml greenter, me genera esta etiqueta xml por ejemplo
<cbc:InvoiceTypeCode listID="0101">01</cbc:InvoiceTypeCode>

pero veo en otros xml y en el manual de la sunat que tiene unos datos adicionales por ejemplo:
  <cbc:InvoiceTypeCode listID="0101"
                       listAgencyName="PE:SUNAT"
                       listName="SUNAT:Identificador de Tipo de Documento"
                       listURI="urn:pe:gob:sunat:cpe:see:gem:catalogos:catalogo01">01</cbc:InvoiceTypeCode>
La pregunta sería si de las 2 formas me la aceptaria la SUNAT en producción??

**Comment by giansalex** [comment]
Si, ambas son aceptables, que son opcionales.

**Comment by JHONQUISPEFLORES** [comment]
muchas griacias @giansalex.
