### ISSUE TITLE
ERROR DE INSTALACION

### ISSUE THREAD

**Issue by byJuanjo** [giansalex/greenter-sample#43]
Hola amigo me baje tu libreria de ejemplo y me sale los siguientes errores al consultar el envio de factura o cualquier otro elemento me sale este error:

![captura de pantalla 2018-10-30 a la s 09 28 11](https://user-images.githubusercontent.com/21320001/47725252-3a502900-dc26-11e8-8c43-fb5fec716ceb.png)

Y al momento de querer generar el pdf me sale este otro error, recien estoy comenzando hacer las pruebas con la misma.

![captura de pantalla 2018-10-30 a la s 09 28 23](https://user-images.githubusercontent.com/21320001/47725301-4d62f900-dc26-11e8-8ada-c56abbba3157.png)

Aprovecho para agradecerte el gran trabajo que estas realizando y no dudes recibir mi donación cuand o termine mi proyecto y me caiga un billetito 👍

**Comment by giansalex** [comment]
Hola @byJuanjo, ocurre cuando no puede conectarse a SUNAT, podrías volver a intentar.
Acerca del PDF, que sistema operativo tienes?

**Comment by byJuanjo** [comment]
Hola @giansalex  gracias por la pronta respuesta, es Mac Os, pero justo voy hacer una prueba con una computadora con Windows, con respecto al primer error, lo vengo presentando desde hace 2 dias, tu crees q solo se debe al tema de que no se puede conectar con la sunat, no hay algun cambio adicional que tenga que realizar en mi local?

**Comment by giansalex** [comment]
Acerca del PDF, solo había dado soporte para windows y linux; para que funcione en tu caso, debes instalar [wkhtmltopdf](https://wkhtmltopdf.org/downloads.html).

En la imagen, el mensaje de error indica que no se puede conectar al host, se refiere al servicio de SUNAT,  talvez haya algún problema con tu red, ya que en herokuapp no aparece el mensaje.

**Comment by byJuanjo** [comment]
Si es mi sistema operativo, ahorita lo instale en una computadora con Windows y si funciono pero al subirlo a un servidor me genera el PDF los XML, pero me sale el mismo error :( 

No se que pueda ser.

![captura de pantalla 2018-10-30 a la s 11 11 09](https://user-images.githubusercontent.com/21320001/47732683-b487aa00-dc34-11e8-91b8-e5a443023e62.png)

**Comment by giansalex** [comment]
Ingrese a la ruta que sale en la imagen, y sí responde para los otros servicios (Percepcion/Retencion y Guia), el problema al parecer es el servicio para Facturas (+BOL, NCR, Bajas, Resumen)

**Comment by giansalex** [comment]
El detalle es que en [Greenter-Sample](https://greenter-sample.herokuapp.com/) si funciona, tendrias que depurar y ver si hay algún mensaje que pueda ayudar: `var_dump($e);` en esta [linea](https://github.com/giansalex/greenter-ws/blob/4cafb9c7c670a0e14e6a802876b1131301dd55a1/src/Ws/Services/BillSender.php#L43) 
Podrias hacerlo en la mac, que tiene el mismo problema.

**Comment by byJuanjo** [comment]
En el servidor me sale este error.

Dime en el PHP que cuales son las extensiones que debo activar aparte del 

SOAP
XML
DOM
ZIp

![captura de pantalla 2018-10-30 a la s 12 09 01](https://user-images.githubusercontent.com/21320001/47736393-9b82f700-dc3c-11e8-9707-911915d08b6e.png)

**Comment by giansalex** [comment]
Si ejecutas `composer install`, alli te indica las extensiones, pero entiendo que en un hosting no siempre se tiene acceso por consola, veré en agregar la lista de extensiones necesarias.
Tambien es necesario openssl activada, pero es raro ya que en los demás servicios cuyo proceso es igual y tienen los mismos requerimientos no produce error

**Comment by byJuanjo** [comment]
Voy activarle el https, a ver si asi funciona.

**Comment by leog1992** [comment]
Estimado, lo subí a un hosting de Godaddy plan mensual, y tampoco genera el xml, sale error al ejecutar script. En mi locahost normal funciona

**Comment by leog1992** [comment]
estimado, encontre en el log de mi hosting q falta la extension zip voy a probar si es solo eso. 
![captura de pantalla_2018-11-04_21-36-05](https://user-images.githubusercontent.com/8444234/47974935-bb218180-e079-11e8-8251-8b0d2836c285.png)

**Comment by leog1992** [comment]
hable pronto, seguimos con el error del zip

**Comment by giansalex** [comment]
pero si pudiste activar la extensión zip?

**Comment by leog1992** [comment]
al parecer hay un modulo q se llama php pear, ese no es , estaba haciendolo mal, fui a seleccionar version y me salio q extensiones usar y alli recien lo active. ahora si. eres un genio. 
![captura de pantalla_2018-11-04_21-52-21](https://user-images.githubusercontent.com/8444234/47975491-0b014800-e07c-11e8-9dd5-a3395c725f18.png)
![captura de pantalla_2018-11-04_21-53-43](https://user-images.githubusercontent.com/8444234/47975509-1d7b8180-e07c-11e8-8509-2a4d97a74e97.png)

**Comment by leog1992** [comment]
desde mi sistema envio los datos como json a greenter sample y todo bien. 
![captura de pantalla_2018-11-04_21-58-27](https://user-images.githubusercontent.com/8444234/47975680-cfb34900-e07c-11e8-8dbd-1f6ebadae092.png)

**Comment by giansalex** [comment]
Que bien
