### ISSUE TITLE
URL de WebService SUNAT

### ISSUE THREAD

**Issue by rhinoperu** [giansalex/greenter-sample#44]
hola he intentando enviar a la sunat y me mando este error
object(Greenter\Model\Response\Error)[115]
  protected 'code' => string 'env:Client' (length=10)
  protected 'message' => string 'Internal Error' (length=14)

**Comment by giansalex** [comment]
Hola @rhinoperu, esto suele ser un error en el servicio de Sunat, podrias esperar y volver a intentar.
Esta relacionado a #43 , que sistema operativo estas usando?

**Comment by giansalex** [comment]
ese error sucede en el servicio de producción?

**Comment by giansalex** [comment]
y porque usas **WSDL_ENDPOINT**?, allí recibe la ruta del servicio de sunat, si es para produccion usa `SunatEndpoints::FE_PRODUCCION `

**Comment by rhinoperu** [comment]
ahora manda esto a que se debe
No tiene el perfil para enviar comprobantes electronicos - Detalle: Rejected by policy.

**Comment by rhinoperu** [comment]
Una pregunta donde pongo el usuario, he estado buscando el error que indica y es por el usuario segun la informacion que busque, donde se configura el usuario gracias

**Comment by giansalex** [comment]
hay una linea de codigo donde se configura:
```php
$see->setCredentials('20000000001MODDATOS', 'moddatos');
```
https://giansalex.github.io/greenter/starter/
