### ISSUE TITLE
detalle en comunicación de bajas

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#45]
hola amigo, debido a las diferencias que hay en beta y producción estoy haciendo "pruebas solo en produccion", acabo de enviar una factura y al querer darle de baja me sale este error:
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Util::getResponseFromCdr() must be an instance of Greenter\Model\Response\CdrResponse, null given, called in C:\xampp\htdocs\mvc\models\facturas_model.php on line 106 and defined in C:\xampp\htdocs\mvc\src\Util.php:46

al parecer hay una respuesta pero con el script que tengo no logro capturarlo (no se si es succes o no o es succes false o true).
en este caso como obtendria esa respuesta ?

public function generar_baja($RA)
	{

			$util = Util::getInstance();
			// Envio a SUNAT.
			$see = $util->getSee(SunatEndpoints::FE_PRODUCCION);
			$res = $see->send($RA);
			
			if ($res->isSuccess()) {
			$ticket = $res->getTicket();
			
			$result = $see->getStatus($ticket);
			if ($result->isSuccess()) {
			$cdr = $result->getCdrResponse();
			$nexus = "|".$util->getResponseFromCdr($cdr);    - > aca da el error 
			$this->sms = "correcto".$nexus;
			
			Util::writeXml($RA, $see->getFactory()->getLastXml());
			$pdf = $util->getPdf($RA);
			$util->showPdf($pdf, $RA->getName().'.pdf');  
			Util::writeCdr($RA, $result->getCdrZip());                               
			} else {
			$this->sms = $ticket."|".$nexus;
			}
			}else {
            
			$this->sms = $res->getError()->getMessage();
			
			}
	
		return $this->sms;	
	}

**Comment by giansalex** [comment]
Podrias verificar que `getCdrResponse` sea diferente de null, existe un campo `$result->getCode()`, que indica sunat aun lo esta procesando (code=98).
> Esto puede ser otra mejora, tener muchos estados es un dolor de cabeza, cuando sea el codigo 98, tomarlo como error y que diga: Esta siendo procesado.
![image](https://user-images.githubusercontent.com/14926587/48034676-612ec380-e12e-11e8-8ac7-f34514d59405.png)
