### ISSUE TITLE
Limite de días para enviar boletas

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#47]
hola amigo, que pasa o que se debe hacer cuando no se envian algunas boletas, mas especificamente resumenes diarios de algunos dias.
se estuvieron enviando resumenes diarios todos los dias y en algunos dias se enviaba pero no habia cdr(por error de sistema) y no fueron declarados ahora de eso ya pasaron mas de 15 o 20 dias, que se hace con esas boletas que no fueron enviadas ya que la numeración continuo y se "salteo" algunas boletas

**Comment by giansalex** [comment]
Segun la norma es 7 dias maximo, pero creo que Sunat permite el envio de resumen sin considerar los dias pasados, puedes intentar enviarlo

**Comment by abelnexus** [comment]
bueno haré la prueba de todos modos, pero supongo que ya no se podra declarar para el mes de octubre(el mes que debieron ser enviadas) si no para noviembre. mañana toca declarar y solo declararan las boletas que tiene cdr, espero no haya problemas con sunat
