### ISSUE TITLE
S.O.S

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#5]
llevo dias intentando crear las facturas,firmarlas,enviarlas desde un formulario y nada :''(

**Comment by giansalex** [comment]
cual es el problema que se te presenta.

**EXT**
si tienes algún mensaje de error podrias mostrarlo.

**Comment by abelnexus** [comment]
puedo enviar datos desde un formulario mediante post y lo capturo en examples/factura.php
el detalle es como hago si quiero  enviar mas de 1 item(por que por formulario solo envio 1)

**Comment by abelnexus** [comment]
![captura](https://user-images.githubusercontent.com/34687414/35003321-835d7b8c-faba-11e7-8d94-c223513ac160.PNG)

**Comment by abelnexus** [comment]
COMO SERIA PARA MEDIANTE FORMULARIO INGRESAR VARIOS ITEMS
![captura](https://user-images.githubusercontent.com/34687414/35003811-f7658b36-fabb-11e7-8ccb-337487dc015c.PNG)

**Comment by giansalex** [comment]
Puedes usar este plugin de jquery http://www.jtable.org/ ,

**Comment by giansalex** [comment]
Puedes usar diferentes formas de llenar la informacion, te recomendaria que lo manejaras con json - jquery-ajax, o puedas utilizar angularjs, etc.

**Comment by abelnexus** [comment]
me falta mucho aprender programación :( gracias
