### ISSUE TITLE
Verificacion de estado de comprobantes emitidos

### ISSUE THREAD

**Issue by aeanez** [giansalex/greenter-sample#50]
Saludos @giansalex,

Existe alguna forma de verificar ante la SUNAT el estado de los comprobantes emitidos (que no sea por la web de consulta validez)? ya que he podido darme cuenta que el ambiente de produccion no es tan estable como desarrollo y en algunos casos no se reciben las respuestas deseadas.

La SUNAT tiene disponibles 2 WS y no se si estan implementados en greenter

WS de consultas de validez y verificación de facturas electrónicas
https://e-factura.sunat.gob.pe/ol-it-wsconsvalidcpe/billValidService?wsdl

WS de consulta de CDR y estado de envío
https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService?wsdl

**Comment by giansalex** [comment]
Hola @aeanez, aqui hay un [ejemplo](https://greenter-sample.herokuapp.com/examples/pages/status-cdr.php) de consulta de estado de comprobante, pero solo es valido para facturas y sus notas de credito/debito relacionadas, es decir comprobantes que tengan serie **FXXX**

**Comment by aeanez** [comment]
Probare, lo vi hace unos dias pero me causo confusion que solicitara 2 veces el RUC

**Comment by giansalex** [comment]
Uno es para las credenciales (clave SOL), y el otro es para la consulta en si, estos ruc pueden ser diferentes si el consulta es un PSE por ejemplo.
