### ISSUE TITLE
Problema al generar XML de boleta

### ISSUE THREAD

**Issue by aeanez** [giansalex/greenter-sample#52]
Saludos, estoy intentanto generar un xml de boleta pero me genera el archivo vacio, de que forma puedo hacer debug de este proceso ya que no me muestra ningun error de php y para la facturas si funciona sin problemas.

**Comment by giansalex** [comment]
Hola @aeanez, si tienes configurado `xdebug` puedes usarlo, o también puedes hacer seguimiento con `var_dump` .

**Comment by aeanez** [comment]
incluso me he fijado que tanto para boleta como para factura se genera el archivo en blanco y al hacer un var_dump no me muestra nada, estoy haciendo lo siguiente:

var_dump($see->getFactory()->getLastXml());

**Comment by aeanez** [comment]
y la respuesta es NULL

**Comment by aeanez** [comment]
en la funcion donde se escribe el XML, imprimo el contenido y me muestra lo siguiente

![image](https://user-images.githubusercontent.com/46237055/51079690-6ca3eb00-1699-11e9-90e3-12668575c2df.png)

![image](https://user-images.githubusercontent.com/46237055/51079705-a2e16a80-1699-11e9-9c77-2e2e85ae51e0.png)

**Comment by aeanez** [comment]
Me doy cuenta que es e contenido del ZIP el que esta imprimiendo pero no dle XML

**Comment by aeanez** [comment]
Dandole vueltas al asunto me doy cuenta que el XML se genera despues de 

$res = $see->send($invoice);

Pero entiendo que "send()" envia a la SUNAT el comprobante, ahora surge una duda, tengo entendido que las boletas se deben enviar a la SUNAT en un resumen pero siguiendo esta forma la boleta se enviaria al momento de generarse, entonces como seria el proceso correcto?

Generar un xml por cada boleta o generar un xml con todas las boletas?

De ser la 2da valida deberia entonces guardar serializado el objeto $invoice de las boletas y luego obtenerlas y enviarlas en el resumen?

Gracias por la dedicacion al proyecto.

**Comment by giansalex** [comment]
Esta relacionado ha este issue https://github.com/giansalex/greenter/issues/56
Las boletas no se envian a sunat, se debe usar otro metodo para generar solo xml.

**Comment by aeanez** [comment]
Entendido, ahora solo por referencia este XML que se genera de forma individual tambien se enviara a la sunat en el resumen (junto con todos los que se generen)? o solo se envia un XML?

**Comment by giansalex** [comment]
El resumen diario es solo un XML, no se envian xml de boletas
