### ISSUE TITLE
 error 4006. Guias de Remisión en Facturas

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [giansalex/greenter-sample#54]
hola @giansalex , tengo una interrogante, como soluciono el error 4006.
4006 - El ID de las guias debe tener informacion de la SERIE-NUMERO de guia. - Guia Relacionada : 09-001-00009536: 4006 (nodo: "cac:DespatchDocumentReference/cbc:ID" valor: "001-00009536")

Le estoy enviando : $valor['tipo_de_documento']=9 y $valor['numero_de_guia'= "001-00009536"
///dentro de un foreach///
$guias = new Document();
$guias->setTipoDoc($valor['tipo_de_documento'])            
                        ->setNroDoc($valor['numero_de_guia']);
  $var_items_guias[]=$guias;
                     $guias=null;
/////////////////////////// 
///y al al finar le asigno todo el array
$invoice->setGuias($var_items_guias);

Si me pudieras ayudar en donde esta mi error. pareciera que no envia el valor del tipo de doc?

**Comment by giansalex** [comment]
Hola Jhon, la serie debe tener 4 dígitos.
Los formatos validos son:
- [T][0-9]{3}-[0-9]{1,8}
- [0-9]{4}-[0-9]{1,8}
- [EG][0-9]{2}-[0-9]{1,8}
- [G][0-9]{3}-[0-9]{1,8}
> Mas información en el excel de validaciones de [SUNAT](http://cpe.sunat.gob.pe/).
