### ISSUE TITLE
detalle con boletas de sumas altas

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#55]
hola amigo, acaba de salirme un error al momento de enviar el resumen diario
genere una boleta de 2099.97 y me bota este error
![asdasd](https://user-images.githubusercontent.com/34687414/54567017-849d3100-49a0-11e9-8fe3-898d54dc12d5.PNG)

**Comment by giansalex** [comment]
Alli en tipo, debe ir `1` - DNI, `6` - RUC, no Boleta.

**Comment by abelnexus** [comment]
si acabo de darme cuenta de este error, pero es la primera vez que ocurre y todos los demas resumenes diarios los envie asi D: , como pudo aceptar los demas ...

**Comment by giansalex** [comment]
A partir de s/. 700, sunat exige que el cliente este identificado, probablemente aplica la validacion dependiendo del monto.
