### ISSUE TITLE
consulta sobre error en comunicación de baja en hosting compartido

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [giansalex/greenter-sample#59]
buenas tardes @giansalex , a que crees que me falte:
Warning: DOMDocument::loadXML(): input conversion failed due to input error, bytes 0x81 0x4C 0x43 0x55 in /home2/jquispe/dominio.com/facturador_ok/vendor/greenter/xmldsig/src/Sunat/SignedXml.php on line 292

Warning: DOMDocument::loadXML(): input conversion failed due to input error, bytes 0x81 0x4C 0x43 0x55 in /home2/jquispe/dominio.com/facturador_ok/vendor/greenter/xmldsig/src/Sunat/SignedXml.php on line 292

Warning: DOMDocument::loadXML(): encoder errorCData section not finished ERROR EN in Entity, line: 49 in /home2/jquispe/dominio.com/facturador_ok/vendor/greenter/xmldsig/src/Sunat/SignedXml.php on line 292

Warning: DOMDocument::loadXML(): Premature end of data in tag VoidReasonDescription line 49 in Entity, line: 49 in /home2/jquispe/dominio.com/facturador_ok/vendor/greenter/xmldsig/src/Sunat/SignedXml.php on line 292

Warning: DOMDocument::loadXML(): Premature end of data in tag VoidedDocumentsLine line 44 in Entity, line: 49 in /home2/jquispe/dominio.com/facturador_ok/vendor/greenter/xmldsig/src/Sunat/SignedXml.php on line 292

Warning: DOMDocument::loadXML(): Premature end of data in tag VoidedDocuments line 2 in Entity, line: 49 in /home2/jquispe/dominio.com/facturador_ok/vendor/greenter/xmldsig/src/Sunat/SignedXml.php on line 292
{"code":"2075","cdsc":"El XML no contiene el tag o no existe informacion de UBLVersionID - Detalle: xxx.xxx.xxx value='ticket: 1554766571217 error: No existe el tag UBLVersionID'","codigo_error":"2075","error":"El XML no contiene el tag o no existe informacion de UBLVersionID - Detalle: xxx.xxx.xxx value='ticket: 1554766571217 error: No existe el tag UBLVersionID'"}

**Comment by giansalex** [comment]
Podrias probar generando solo el XML sin firmar, y compartirlo.

**Comment by JHONQUISPEFLORES** [comment]
![image](https://user-images.githubusercontent.com/31812268/55764458-31fbe580-5a31-11e9-8a55-3bc720e2c378.png)

**Comment by JHONQUISPEFLORES** [comment]
haber voy a probar sin firmado.

**Comment by JHONQUISPEFLORES** [comment]
me sale igual, sin firmarlo. en modo local si me funciona todo.

**Comment by JHONQUISPEFLORES** [comment]
me sale solo la linea uno. sin firmado

**Comment by JHONQUISPEFLORES** [comment]
debe ser k me falta asignarle algun valor mas, xk hice la prueba con la comunicac. de prueba y si funciona.
![image](https://user-images.githubusercontent.com/31812268/55766020-3d9eda80-5a38-11e9-8b68-85318cf420ad.png)

**Comment by giansalex** [comment]
intenta borrando la carpeta cache, y que esta tenga permisos de escritura en el servidor.

**Comment by JHONQUISPEFLORES** [comment]
HOLAS @giansalex ,  ENCONTRE EL ORIGEN DEL ERROR: EN EL CAMPO "DesMotivoBaja" LE COLOQUE: "ERROR EN CÁLCULOS" CON TILDE. QUIERE DECIR QUE DEBO SUPRIMIR LAS TILDES PARA QUE NO ME GENERE EL ERROR.

**Comment by giansalex** [comment]
Hola @JHONQUISPEFLORES , el problema ha sido por la codificación que indica en el header del XML.  [/src/Xml/Templates/voided.xml.twig#L1](https://github.com/giansalex/greenter-xml/blob/07ec75ee847f4b3dea3913e499c05d26be43475a/src/Xml/Templates/voided.xml.twig#L1)
Debe estar como UTF-8 al igual que en facturas.

**Comment by JHONQUISPEFLORES** [comment]
Y EN SUMARY DICE encoding="ISO-8859-1", IMAGINO K TAMBIÉN

**Comment by giansalex** [comment]
@JHONQUISPEFLORES  asi es, la corrección es para todas las plantillas.
Se ha hecho la correcion en https://github.com/giansalex/greenter-xml/commit/d125084235c1f583f7303ee83d036931e7537332 , puedes ejecutar `composer update`
