### ISSUE TITLE
No puedo obtener CDR en Resumen de boletas - code 0127 en Producción

### ISSUE THREAD

**Issue by Redlein** [giansalex/greenter-sample#60]
Qué tal @giansalex, un trabajo genial el que realizaste.
Tengo una duda, al enviar el resumen diario y consultar su estado al instante, algunas veces obtengo el code 0 y otras el 98 en este caso no obtengo el CDR, antes de obtener el estado ya he guardado el ticket para poder consultarlo luego pero cuando quiero consultar el ticket siempre me aparece el code 0127 "El ticket no existe", qué estoy haciendo mal?
Gracias de antemano.

![image](https://user-images.githubusercontent.com/7254689/55777238-01ce3a00-5a65-11e9-9ac7-a88cdc39d2dc.png)

![image](https://user-images.githubusercontent.com/7254689/55777197-dfd4b780-5a64-11e9-9bc6-df9c03b22c06.png)

**Comment by giansalex** [comment]
El procedimiento que indicas está bien, tal vez sea un problema de sunat.
Corrobora que no estés enviando el ticket de otro resumen.

**Comment by Redlein** [comment]
Sí envío el ticket correcto, parece como si el ticket tuviera tiempo de vida, con el usuario sol puedo ver que las boletas sí han Sido informadas, solamente no puedo obtener el cdr de las que me salieron code 98 :(

**Comment by giansalex** [comment]
Eso no debería ocurrir, pero tal vez dando un poco mas de tiempo para consulta del estado el CDR, evite que te aparezca el código 98.

**Comment by djdnl13** [comment]
Me sucede lo mismo. Puede que la consulta tengas que hacerla (5~30)segundos despues. Al parecer los servidores de validación demoran un poco en dar respuesta o algunas veces están en sleep mode(en este caso no devuelven ticket).

La unica solucion que encontré es guardar el nro de ticket que se genera y consultarlo posteriormente.

**Comment by giansalex** [comment]
@djdnl13 segun lo que dice @Redlein guarda el ticket, consulta la primera vez y le retorna codigo 98, vuelve a consultar y le aparece el mensaje de "No existe el ticket". También creo que una forma de evitarlo seria dando mas tiempo antes de consultar.

**Comment by thefantas** [comment]
Hola, que pena abrir el post, pero es un tema muy parecido.
Sunat logra dar un ticker a un RA o RC, (ejm, 3000000X93X94X5) pero al consulta, 127 no existe el ticket.. o sea, el problema ya no es que no te de un ticket sino que te da uno que no es el correcto, ya que posteriormente en el portal de SUNAT reviso la baja de ese documento y se ejecutó correctamente pero con un ticket totalmente distinto (ejm,  201909612992649), que al actualizar el ticket en la consulta obtengo la respuesta deseada, que existe y ha sido aceptada.

La consulta es, cómo obtener el ticket correcto? hay alguna forma de automatizarlo? ya que por ahora se hace manualmente, estoy seguro a más de uno le ha pasado.

Saludos.
