### ISSUE TITLE
Enviar Resumen Diario en Bloque

### ISSUE THREAD

**Issue by abelespi** [giansalex/greenter-sample#61]
Hola Amigo, necesito de tu valiosa ayuda, como hago para enviar el resumen de boletas de todo el dia, por ejemplo quiero enviar (Quiero enviar las los números de boleta de 1 al 104 generados en un solo dia). Por favor podrías indicarme ya que en el ejemplo no encuentro como poner el StartDocumentNumberID y EndDocumentNumberID saludos y espero tu valiosa respuestas

**Comment by giansalex** [comment]
Esos campos ya no se usan, es del ubl 2.0, actualmente sunat exige la version ubl 2.1, alli cada detalle representa una boleta/ncr/ndb

**Comment by abelespi** [comment]
entre los archivos no hay la version 2.1 solo 2.0 donde puedo adquirir esa version porfa??

**Comment by giansalex** [comment]
Disculpa era CustomizationID 1.1, es el mismo que está en el ejemplo de este repositorio

**Comment by abelespi** [comment]
Disculpa, yo descargue todo y no encuentro o no veo CustomizationID 1.1, me podria decir por favor donde se encuentra o tal vez descargue mal.

**Comment by giansalex** [comment]
Este en este archivo [summary.xml.twig](https://github.com/giansalex/greenter-xml/blob/d125084235c1f583f7303ee83d036931e7537332/src/Xml/Templates/summary.xml.twig#L16), pero según tu pregunta inicial, el ejemplo de resumen esta en este repositorio, en el archivo [/examples/resumen.php](https://github.com/giansalex/greenter-sample/blob/master/examples/resumen.php)

**Comment by abelespi** [comment]
Gracias por el dato, pero dime una cosa no habra o tendras algun ejemplo para poder enviar el resumen por bloques es decir de un dia entero por ejemplo. Te lo voy a agradecer mucho si me ayudas en esto.
