### ISSUE TITLE
Formato de fecha de emisión facturas

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [giansalex/greenter-sample#62]
buenas tardes @giansalex , una consulta estoy enviando una fecha antigua;
$invoice_fecha_de_emision='2019-04-02';
$invoice_hora_de_emision='20:44:24';
pero estoy utilizando la sgte linea
->setFechaEmision(new \DateTime($invoice_fecha_de_emision+' '+$invoice_hora_de_emision))

pero me muestra la fecha actual dehoy, que podria hacer??

**Comment by giansalex** [comment]
En php para concatenar cadenas se usa `.`, no `+`

**Comment by JHONQUISPEFLORES** [comment]
gracias, tenias razón. me confundí con el javascript, y no vi el error del "+" por el ".".
