### ISSUE TITLE
Error al generar xml y su respuesta cdr, en digital ocean.

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [giansalex/greenter-sample#63]
En un hosting compatido funciona normal.
pero en digital ocean le instale php5.6, php5.6-soap, openssl, zip. estoy viendo k no responde en $res = $see->send($invoice);
print_r($res); // hice estas pruebas y me parece k es en el send xk no tiene respuesta.
exit(); 
![image](https://user-images.githubusercontent.com/31812268/56461436-aa8b6c00-6378-11e9-80ca-a96656053e29.png).

**Comment by JHONQUISPEFLORES** [comment]
comparto mi phpinfo, por siacaso alguien pueda ayudarme
http://138.68.238.34/phpinfo.php

**Comment by JHONQUISPEFLORES** [comment]
@giansalex active la visualizacion de errores de php y me salio esto:
Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/html/facturador_ok/src/../cache/07).' in /var/www/html/facturador_ok/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:55 Stack trace: #0 /var/www/html/facturador_ok/vendor/twig/twig/lib/Twig/Environment.php(457): Twig_Cache_Filesystem->write('/var/www/html/f...', '<?php\n\n/* invoi...') #1 /var/www/html/facturador_ok/vendor/twig/twig/lib/Twig/Environment.php(363): Twig_Environment->loadTemplate('invoice2.1.xml....') #2 /var/www/html/facturador_ok/vendor/greenter/xml/src/Xml/Builder/TwigBuilder.php(42): Twig_Environment->render('invoice2.1.xml....', Array) #3 /var/www/html/facturador_ok/vendor/greenter/xml/src/Xml/Builder/InvoiceBuilder.php(34): Greenter\Xml\Builder\TwigBuilder->render('invoice2.1.xml....', Object(Greenter\Model\Sale\Invoice)) #4 /var/www/html/facturador_ok/vendor/greenter/greenter/src/Greenter/Factory/FeFactory.php(153): Greenter\Xml\Builder\InvoiceBuilder->build(Object(Greenter\Model\Sale\Invoice in /var/www/html/facturador_ok/vendor/twig/twig/lib/Twig/Cache/Filesystem.php on line 55

**Comment by JHONQUISPEFLORES** [comment]
solucionado esa parte, eran por los prmisos
![image](https://user-images.githubusercontent.com/31812268/56465014-15f62d80-63bb-11e9-8fd6-8888bb4fef4c.png)

**Comment by giansalex** [comment]
Puedes dar permiso de escritura a la carpeta cache/
