### ISSUE TITLE
duda con Nota de débito

### ISSUE THREAD

**Issue by rafnolo** [giansalex/greenter-sample#66]
Buenas noches, 
Tengo una duda con la nota de débito:
https://github.com/giansalex/greenter-sample/blob/master/examples/nota-debito.php
Básicamente es en la línea 15:
->setCompra('0014232')
¿Qué información debo completar aquí?

**Comment by giansalex** [comment]
Hola @rafnolo, es una orden de compra que este relacionada pero no es obligatorio.
Trataré de actualizar los ejemplos, para usar solo los campos indispensables para la emisión.

**Comment by giansalex** [comment]
close https://github.com/giansalex/greenter-sample/commit/9fa4c0abba730a2ae4d408ffbd9388d64b036bb9
