### ISSUE TITLE
Decimales en cantidad - invoice detalle

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#67]
hola amigo, es posible enviar un producto que tenga su cantidad en 1.3 ? hize las pruebas en beta y normal me acepta pero no se en producción sunat permite eso o tendre problemas mas adelante?

**Comment by giansalex** [comment]
Hola, segun la validaciones de sunat, permite hasta 10 decimales
![image](https://user-images.githubusercontent.com/14926587/58670028-4c509200-8303-11e9-9322-6dfc8ca33fcc.png)

**Comment by abelnexus** [comment]
me acepto la factura pero me observo 2 cosas:
<cbc:Note>4288 - El valor de venta por ítem difiere de los importes consignados. - Error en la linea: 5: 4288 (nodo: "cac:InvoiceLine/cbc:LineExtensionAmount" valor: "13984.32")</cbc:Note>

<cbc:Note>4288 - El valor de venta por ítem difiere de los importes consignados. - Error en la linea: 7: 4288 (nodo: "cac:InvoiceLine/cbc:LineExtensionAmount" valor: "2118.64")</cbc:Note>

**Comment by giansalex** [comment]
Eso probablemente es por tema de sumas.

**Comment by fertandil87** [comment]
@giansalex tengo el mismo problema que vos. Como lo solucionaste? en mi caso solo me pasa cuando hago notas de credito de boletas con items con descuento
