### ISSUE TITLE
Bad Gateway 

### ISSUE THREAD

**Issue by Ajahuanex** [giansalex/greenter-sample#68]
Durante el día probé conectarme a la sunat sin exito, posiblemente es algo temporal ó cambiaron la URLs de prueba?, 
![Screenshot_24](https://user-images.githubusercontent.com/2767765/58906750-390e3f80-86d2-11e9-8d8e-c6fd3aa743ee.png)

Sin embargo, desde Guias de Remisión están activos.
![Screenshot_25](https://user-images.githubusercontent.com/2767765/58906892-9acea980-86d2-11e9-90a8-3947c8e65adf.png)

**Comment by giansalex** [comment]
Hola @Ajahuanex , hay varios servicios de sunat, el de guia de remision y percepcion son diferentes, es por ello que funciona en uno y no en el otro. Pero alli solo queda esperar a que vuelva estar activo.
> Tendré pendiente agregar la sección de preguntas y respuestas comunes, y evitar confusiones.
