### ISSUE TITLE
problemas al enviar boletas con estado anulado

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#70]
cuando trato de enviar el resumen diario con alguna boleta con estado anulado me bota null como respuesta siempre,
 $mensajeError = $result->getError(); - esto uso para obtener la respuesta y me da null.
si uso esto:
$result->getError()->getMessage(); me bota este error:
<b>Fatal error</b>:  Uncaught Error: Call to a member function getMessage() on null in C:\xampp\htdocs\arkialum\controllers\resumen_diario.php:212
Stack trace:

esta varios dias, semanas asi

**Comment by abelnexus** [comment]
esto uso para enviar el estado de si es anulado o no:
 if($value['estado'] == "GENERADO"){
                    $estado = "1";
                  }
                  else if($value['estado'] == "MODIFICADO"){
                    $estado = "2";
                  }
                  else if($value['estado'] == "ANULAR"){
                    $estado = "3";
                  }

**Comment by giansalex** [comment]
Puedes hacer un `var_dump($result)`

**Comment by abelnexus** [comment]
object(Greenter\Model\Response\StatusResult)#141 (5) {
  ["code":protected]=>
  string(4) "0098"
  ["cdrZip":protected]=>
  NULL
  ["cdrResponse":protected]=>
  NULL
  ["success":protected]=>
  bool(true)
  ["error":protected]=>
  NULL
}

**Comment by abelnexus** [comment]
revisando las boletas vi que una boleta de mas de 1000 s/ no tiene un dni valido, puede ser por eso pero asi sea el caso no envia un mensaje de error sobre eso ?

**Comment by giansalex** [comment]
Es por que el resumen aun no esta listo

![image](https://user-images.githubusercontent.com/14926587/61836237-f13fa500-ae44-11e9-94d0-a363c502709d.png)

**Comment by abelnexus** [comment]
ya le cambie por dni´s validos y hasta ahora nada: se queda en:
 Error: La numeracion o nombre del documento ya ha sido enviado anteriormente - Detalle: xxx.xxx.xxx value='ticket: error: El documento: 20603655941-RC-20190726-00000062 ya fue enviado y se encuentra en estado 98; por favor espere a que se termine de procesar el envio.'
desde el 59 esta asi y hasta ahora no me acepta, use el 59,60, y 61 y no me da el cdr hasta ahora ni me carga el sunat sol las boletas enviadas

**Comment by giansalex** [comment]
Debes volver a consultar el estado, con `getStatus`, y si no muestra las boletas en el portal parece ser un problema con sunat, o algun OSE que estes usando?

**Comment by thefantas** [comment]
He tenido detalles como el tuyo, lo primero es error común de los registradores de clientes, tienes que filtrar los datos con el tipo de documento y tipo de persona según el número de caracteres.
En el último mensaje  de abel se debe a que greenter logró enviar el documento y la sunat lo aceptó pero por diversos motivos no pudiste capturar bien la respuesta y estás volviendo a enviar dándote la respuesta indica en tu comentario.
Como dice Gian, tengo algunos manejadores de errores que me devuelve sunat (para boletas o documentos que permiten corregir y reenviar) donde antes de hacer el segundo intento compruebo su estado (getstatus) y según el resultado lo proceso.

saludos.

**Comment by abelnexus** [comment]
nada aun no puedo solucionar, que ocurre si declaro boletas que no envie a sunat? es alguna multa observacion ?

**Comment by thefantas** [comment]
Entra al portal de la sunat y busca a tu comprobante, con el ese hash puedes recuperar el CDR.
