### ISSUE TITLE
Guía de Remisión

### ISSUE THREAD

**Issue by thefantas** [giansalex/greenter-sample#71]
Hola, una consulta, la guía de remisión se anula con emitiendo otra guía que anula la anterior, con los datos de $baja?<
Porque en el portal solo se consigna 3 campos, tipo de doc, serie número y motivo.

Saludos.

**Comment by giansalex** [comment]
La anulación debería hacerse desde el portal, el campo `$baja` según SUNAT es para `referenciar una guia de remision  (dada de baja por cambio de destinatario)`

**Comment by thefantas** [comment]
Y para cerrar el tema, el documento relacionado del cátologo21 a qué está relacionado, saludos :). Gracias.

**Comment by thefantas** [comment]
https://github.com/giansalex/greenter-sample/issues/54#issuecomment-470296020

**Comment by giansalex** [comment]
Ese comentario estaba relacionado al formato de guia de remisión que se puede referenciar en una factura electrónica. Aunque el primer formato definitivamente debe ser `[T][A-Z0-9]{3}-[0-9]{1,8}`
Ten en cuenta que los PDF de sunat son de hace años, puedes revisar el [excel de validación](http://cpe.sunat.gob.pe/node/88#item-4) para ver la información mas actualizada.

**Comment by BryanP16** [comment]
Buenas, una consulta para emitir una guia de remision con motivo de compra, me indica añadir el proveedor que tag se usa cual es la sintaxis correcta a usar.
Muchas gracias
