### ISSUE TITLE
Resumen diario: El documento indicado no existe no puede ser modificado/eliminado 

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#72]
Buenas tardes cuando trato de enviar el resumen diario con una boleta con estado anulado, me envia este error

**Comment by giansalex** [comment]
Creo que el error es descriptivo, el documento se tendría que enviar previamente como nuevo, luego eliminarlo en otro resumen.

**Comment by abelnexus** [comment]
no entiendo, entonces ya no sirve enviar boletas con estado 02 = anulado ?
entonces tendria que enviar la boleta como 01 y en otro resumen crear la misma boleta pero ahora con 02 ?

**Comment by giansalex** [comment]
si sirver enviar con 02, solo que previamente debes haberla informado con 01
