### ISSUE TITLE
comunicacion de baja: no se puede ler (parsear) el archivo XML

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [giansalex/greenter-sample#73]
Buenas tardes, esta semana no puedo enviar ninguna comunicación de baja me sale el error "no se puede ler (parsear) el archivo XML", no se a que se debe

**Comment by giansalex** [comment]
Hola @JHONQUISPEFLORES , esto puede deberse a que algún código por ejemplo de tipo de moneda no es válida, si tienes el xml puedes usar [ubl-validator](https://github.com/giansalex/ubl-validator-cli), para saber exactamente cual es el error.

**Comment by JHONQUISPEFLORES** [comment]
aunque solo estoy enviando una comunicación de baja, haciendo referencia a una factura

**Comment by giansalex** [comment]
Entonces podrías compartir el xml que envias, porque ese mensaje de error generalmente es por eso. O envias a algun OSE?

**Comment by JHONQUISPEFLORES** [comment]
<VoidedDocuments xmlns="urn:sunat:names:specification:ubl:peru:schema:xsd:VoidedDocuments-1" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:sac="urn:sunat:names:specification:ubl:peru:schema:xsd:SunatAggregateComponents-1" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<ext:UBLExtensions>
<ext:UBLExtension>
<ext:ExtensionContent>
<ds:Signature Id="SignIMM">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<ds:Reference URI="">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>5c6JvTzYTYq/cSGzJJR9qZ1Fg8w=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>
Rzu76XAD1tDn6Lx/q/Ll2lTOwre4EvCIeKWVWrDg7fZ61T/lOZF7DiinT+jdZLp2T28KQgxHu8H82ZRv8CZdd9caBlvepIP5v3LIKSuHfsNlqlU9NXIPi3lJ8ymnIf9PUNkx0ML9RbD9Gs9Au3paUXQ8VV+P9nzUPdLnFTHmux2Px01Ls499HMCWSJJvXcuNaLqzTOD9AUuvpGI1MuY/dTAlD4/g0PMrYPvyAr+65fvtUPPFIlYus/I0GytXRB5TBAm2kTGe01ciZtLYoyL7FKdtYJk1PHtvFyzNzjq+X6pTmD+tFpYOLo1zZhyyL0wbiYlO+sAiY4fa5Q8KDiRvPg==
</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
MIIE/DCCA+SgAwIBAgIIfhLk207wY40wDQYJKoZIhvcNAQELBQAwRjEkMCIGA1UEAwwbTGxhbWEucGUgU0hBMjU2IFN0YW5kYXJkIENBMREwDwYDVQQKDAhMTEFNQS5QRTELMAkGA1UEBhMCUEUwHhcNMTkwMzAyMDAyMDU0WhcNMjAwMzAxMDAyMDU0WjCB1DEgMB4GA1UECQwXQVYuIDI1IERFIE5PVi4gTlJPLiAyMDcxKDAmBgkqhkiG9w0BCQEWGW9maXBhcGVsX2VpcmxAaG90bWFpbC5jb20xITAfBgNVBAMMGFpBUEFUQSBSQU1PUyBXSUxCRVIgSk9TRTERMA8GA1UEBRMIMDQ0MzMzNDQxFDASBgNVBAsMCzIwNTMyNjM5NjgwMRowGAYDVQQKDBFPRklQQVBFTCBFLkkuUi5MLjERMA8GA1UEBwwITU9RVUVHVUExCzAJBgNVBAYTAlBFMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuLHkcdbgsedf82oIRhBkKOnh7B3ExbpqSavUAtebcIkDjSkL318bAfOrNnheQWhcAd/lKIgv3SCWQyYrRPv9BZjkpWpicxVdXbhLsixDx0a+eyrUGngyCP1353GbtTF6eDqko64DEQwg2c7PgEfj7TTJla3sMFmP8M/Pn6nn/cPwd69mRJYuV4bhfYsxBDh36Fwq5VVFlDK2jnNv+vSkqoya6kCgTEWn+UxIHZp4DtlTvC+C+8acTse9vwlpY37dwxL4povaJHwjMiwJjjBI146gv8707mDz48FUEGkOzFIl2uhOJFciNrhLd4v/ELlbztb0/Da0AQ3OtsDrAHkpEwIDAQABo4IBXTCCAVkwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBRdiFut62X7/mii5NlvPVdyou8rmTAwBggrBgEFBQcBAQQkMCIwIAYIKwYBBQUHMAGGFGh0dHA6Ly9vY3NwLmxsYW1hLnBlMCQGA1UdEQQdMBuBGW9maXBhcGVsX2VpcmxAaG90bWFpbC5jb20wRgYDVR0gBD8wPTA7Bg0rBgEEAYOXdwABAAIBMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8vbGxhbWEucGUvcmVwb3NpdG9yeS8wHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMDoGA1UdHwQzMDEwL6AtoCuGKWh0dHA6Ly9jcmwubGxhbWEucGUvbGxhbWFwZXN0YW5kYXJkY2EuY3JsMB0GA1UdDgQWBBSm3H1xB3ZPg04R/2kb9kn7QrpCBzAOBgNVHQ8BAf8EBAMCBsAwDQYJKoZIhvcNAQELBQADggEBACL4730kuy8qfLV50SrvQFfLA8UmYv8kvVt4X8bnx/CtJxc2/+rupfo6XwlogMcmehoImTuoMh8HLoUB2//mzKYexIoYqR6DBj9O8FFSfTr1ufDmpKr8ZQOa1ZeTehyRgwU+h4jc/Xfzec38Zru76x5B+QnEWWo1yQZio554K80kI+F9FORXtH+Tv74ous74iuKB7kqQitnHy7OEoQTovuKAOV4k5K+zhbdsMiaxaP3fTS+rRKZM4JtIaSOu/Z8bqJa2peP5mTDj2XcgW55l+6wXAAywakY1tl8Sx5WClVzWzIXqZ+levI65jFjehmdJnLb3WGB+ghK27PmF17HDR3U=
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</ds:Signature>
</ext:ExtensionContent>
</ext:UBLExtension>
</ext:UBLExtensions>
<cbc:UBLVersionID>2.0</cbc:UBLVersionID>
<cbc:CustomizationID>1.0</cbc:CustomizationID>
<cbc:ID>RA-20191019-001</cbc:ID>
<cbc:ReferenceDate>2019-10-16</cbc:ReferenceDate>
<cbc:IssueDate>2019-10-19</cbc:IssueDate>
<cac:Signature>
<cbc:ID>20532639680</cbc:ID>
<cbc:Note>GREENTER Builder</cbc:Note>
<cac:SignatoryParty>
<cac:PartyIdentification>
<cbc:ID>20532639680</cbc:ID>
</cac:PartyIdentification>
<cac:PartyName>
<cbc:Name>
<![CDATA[ OFIPAPEL E.I.R.L. ]]>
</cbc:Name>
</cac:PartyName>
</cac:SignatoryParty>
<cac:DigitalSignatureAttachment>
<cac:ExternalReference>
<cbc:URI>#SIGN-GREEN</cbc:URI>
</cac:ExternalReference>
</cac:DigitalSignatureAttachment>
</cac:Signature>
<cac:AccountingSupplierParty>
<cbc:CustomerAssignedAccountID>20532639680</cbc:CustomerAssignedAccountID>
<cbc:AdditionalAccountID>6</cbc:AdditionalAccountID>
<cac:Party>
<cac:PartyLegalEntity>
<cbc:RegistrationName>
<![CDATA[ OFIPAPEL E.I.R.L. ]]>
</cbc:RegistrationName>
</cac:PartyLegalEntity>
</cac:Party>
</cac:AccountingSupplierParty>
<sac:VoidedDocumentsLine>
<cbc:LineID>1</cbc:LineID>
<cbc:DocumentTypeCode>01</cbc:DocumentTypeCode>
<sac:DocumentSerialID>F001</sac:DocumentSerialID>
<sac:DocumentNumberID>00001181</sac:DocumentNumberID>
<sac:VoidReasonDescription>
<![CDATA[ ERROR DE DIGITACION ]]>
</sac:VoidReasonDescription>
</sac:VoidedDocumentsLine>
</VoidedDocuments>

**Comment by JHONQUISPEFLORES** [comment]
<VoidedDocuments xmlns="urn:sunat:names:specification:ubl:peru:schema:xsd:VoidedDocuments-1" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:sac="urn:sunat:names:specification:ubl:peru:schema:xsd:SunatAggregateComponents-1" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<ext:UBLExtensions>
<ext:UBLExtension>
<ext:ExtensionContent>
<ds:Signature Id="SignIMM">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<ds:Reference URI="">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>5c6JvTzYTYq/cSGzJJR9qZ1Fg8w=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>
Rzu76XAD1tDn6Lx/q/Ll2lTOwre4EvCIeKWVWrDg7fZ61T/lOZF7DiinT+jdZLp2T28KQgxHu8H82ZRv8CZdd9caBlvepIP5v3LIKSuHfsNlqlU9NXIPi3lJ8ymnIf9PUNkx0ML9RbD9Gs9Au3paUXQ8VV+P9nzUPdLnFTHmux2Px01Ls499HMCWSJJvXcuNaLqzTOD9AUuvpGI1MuY/dTAlD4/g0PMrYPvyAr+65fvtUPPFIlYus/I0GytXRB5TBAm2kTGe01ciZtLYoyL7FKdtYJk1PHtvFyzNzjq+X6pTmD+tFpYOLo1zZhyyL0wbiYlO+sAiY4fa5Q8KDiRvPg==
</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
MIIE/DCCA+SgAwIBAgIIfhLk207wY40wDQYJKoZIhvcNAQELBQAwRjEkMCIGA1UEAwwbTGxhbWEucGUgU0hBMjU2IFN0YW5kYXJkIENBMREwDwYDVQQKDAhMTEFNQS5QRTELMAkGA1UEBhMCUEUwHhcNMTkwMzAyMDAyMDU0WhcNMjAwMzAxMDAyMDU0WjCB1DEgMB4GA1UECQwXQVYuIDI1IERFIE5PVi4gTlJPLiAyMDcxKDAmBgkqhkiG9w0BCQEWGW9maXBhcGVsX2VpcmxAaG90bWFpbC5jb20xITAfBgNVBAMMGFpBUEFUQSBSQU1PUyBXSUxCRVIgSk9TRTERMA8GA1UEBRMIMDQ0MzMzNDQxFDASBgNVBAsMCzIwNTMyNjM5NjgwMRowGAYDVQQKDBFPRklQQVBFTCBFLkkuUi5MLjERMA8GA1UEBwwITU9RVUVHVUExCzAJBgNVBAYTAlBFMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuLHkcdbgsedf82oIRhBkKOnh7B3ExbpqSavUAtebcIkDjSkL318bAfOrNnheQWhcAd/lKIgv3SCWQyYrRPv9BZjkpWpicxVdXbhLsixDx0a+eyrUGngyCP1353GbtTF6eDqko64DEQwg2c7PgEfj7TTJla3sMFmP8M/Pn6nn/cPwd69mRJYuV4bhfYsxBDh36Fwq5VVFlDK2jnNv+vSkqoya6kCgTEWn+UxIHZp4DtlTvC+C+8acTse9vwlpY37dwxL4povaJHwjMiwJjjBI146gv8707mDz48FUEGkOzFIl2uhOJFciNrhLd4v/ELlbztb0/Da0AQ3OtsDrAHkpEwIDAQABo4IBXTCCAVkwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBRdiFut62X7/mii5NlvPVdyou8rmTAwBggrBgEFBQcBAQQkMCIwIAYIKwYBBQUHMAGGFGh0dHA6Ly9vY3NwLmxsYW1hLnBlMCQGA1UdEQQdMBuBGW9maXBhcGVsX2VpcmxAaG90bWFpbC5jb20wRgYDVR0gBD8wPTA7Bg0rBgEEAYOXdwABAAIBMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8vbGxhbWEucGUvcmVwb3NpdG9yeS8wHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMDoGA1UdHwQzMDEwL6AtoCuGKWh0dHA6Ly9jcmwubGxhbWEucGUvbGxhbWFwZXN0YW5kYXJkY2EuY3JsMB0GA1UdDgQWBBSm3H1xB3ZPg04R/2kb9kn7QrpCBzAOBgNVHQ8BAf8EBAMCBsAwDQYJKoZIhvcNAQELBQADggEBACL4730kuy8qfLV50SrvQFfLA8UmYv8kvVt4X8bnx/CtJxc2/+rupfo6XwlogMcmehoImTuoMh8HLoUB2//mzKYexIoYqR6DBj9O8FFSfTr1ufDmpKr8ZQOa1ZeTehyRgwU+h4jc/Xfzec38Zru76x5B+QnEWWo1yQZio554K80kI+F9FORXtH+Tv74ous74iuKB7kqQitnHy7OEoQTovuKAOV4k5K+zhbdsMiaxaP3fTS+rRKZM4JtIaSOu/Z8bqJa2peP5mTDj2XcgW55l+6wXAAywakY1tl8Sx5WClVzWzIXqZ+levI65jFjehmdJnLb3WGB+ghK27PmF17HDR3U=
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</ds:Signature>
</ext:ExtensionContent>
</ext:UBLExtension>
</ext:UBLExtensions>
<cbc:UBLVersionID>2.0</cbc:UBLVersionID>
<cbc:CustomizationID>1.0</cbc:CustomizationID>
<cbc:ID>RA-20191019-001</cbc:ID>
<cbc:ReferenceDate>2019-10-16</cbc:ReferenceDate>
<cbc:IssueDate>2019-10-19</cbc:IssueDate>
<cac:Signature>
<cbc:ID>20532639680</cbc:ID>
<cbc:Note>GREENTER Builder</cbc:Note>
<cac:SignatoryParty>
<cac:PartyIdentification>
<cbc:ID>20532639680</cbc:ID>
</cac:PartyIdentification>
<cac:PartyName>
<cbc:Name>
<![CDATA[ OFIPAPEL E.I.R.L. ]]>
</cbc:Name>
</cac:PartyName>
</cac:SignatoryParty>
<cac:DigitalSignatureAttachment>
<cac:ExternalReference>
<cbc:URI>#SIGN-GREEN</cbc:URI>
</cac:ExternalReference>
</cac:DigitalSignatureAttachment>
</cac:Signature>
<cac:AccountingSupplierParty>
<cbc:CustomerAssignedAccountID>20532639680</cbc:CustomerAssignedAccountID>
<cbc:AdditionalAccountID>6</cbc:AdditionalAccountID>
<cac:Party>
<cac:PartyLegalEntity>
<cbc:RegistrationName>
<![CDATA[ OFIPAPEL E.I.R.L. ]]>
</cbc:RegistrationName>
</cac:PartyLegalEntity>
</cac:Party>
</cac:AccountingSupplierParty>
<sac:VoidedDocumentsLine>
<cbc:LineID>1</cbc:LineID>
<cbc:DocumentTypeCode>01</cbc:DocumentTypeCode>
<sac:DocumentSerialID>F001</sac:DocumentSerialID>
<sac:DocumentNumberID>00001181</sac:DocumentNumberID>
<sac:VoidReasonDescription>
<![CDATA[ ERROR DE DIGITACION ]]>
</sac:VoidReasonDescription>
</sac:VoidedDocumentsLine>
</VoidedDocuments>

**Comment by JHONQUISPEFLORES** [comment]
`<VoidedDocuments xmlns="urn:sunat:names:specification:ubl:peru:schema:xsd:VoidedDocuments-1" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:sac="urn:sunat:names:specification:ubl:peru:schema:xsd:SunatAggregateComponents-1" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<ext:UBLExtensions>
<ext:UBLExtension>
<ext:ExtensionContent>
<ds:Signature Id="SignIMM">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<ds:Reference URI="">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>5c6JvTzYTYq/cSGzJJR9qZ1Fg8w=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>
Rzu76XAD1tDn6Lx/q/Ll2lTOwre4EvCIeKWVWrDg7fZ61T/lOZF7DiinT+jdZLp2T28KQgxHu8H82ZRv8CZdd9caBlvepIP5v3LIKSuHfsNlqlU9NXIPi3lJ8ymnIf9PUNkx0ML9RbD9Gs9Au3paUXQ8VV+P9nzUPdLnFTHmux2Px01Ls499HMCWSJJvXcuNaLqzTOD9AUuvpGI1MuY/dTAlD4/g0PMrYPvyAr+65fvtUPPFIlYus/I0GytXRB5TBAm2kTGe01ciZtLYoyL7FKdtYJk1PHtvFyzNzjq+X6pTmD+tFpYOLo1zZhyyL0wbiYlO+sAiY4fa5Q8KDiRvPg==
</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
MIIE/DCCA+SgAwIBAgIIfhLk207wY40wDQYJKoZIhvcNAQELBQAwRjEkMCIGA1UEAwwbTGxhbWEucGUgU0hBMjU2IFN0YW5kYXJkIENBMREwDwYDVQQKDAhMTEFNQS5QRTELMAkGA1UEBhMCUEUwHhcNMTkwMzAyMDAyMDU0WhcNMjAwMzAxMDAyMDU0WjCB1DEgMB4GA1UECQwXQVYuIDI1IERFIE5PVi4gTlJPLiAyMDcxKDAmBgkqhkiG9w0BCQEWGW9maXBhcGVsX2VpcmxAaG90bWFpbC5jb20xITAfBgNVBAMMGFpBUEFUQSBSQU1PUyBXSUxCRVIgSk9TRTERMA8GA1UEBRMIMDQ0MzMzNDQxFDASBgNVBAsMCzIwNTMyNjM5NjgwMRowGAYDVQQKDBFPRklQQVBFTCBFLkkuUi5MLjERMA8GA1UEBwwITU9RVUVHVUExCzAJBgNVBAYTAlBFMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuLHkcdbgsedf82oIRhBkKOnh7B3ExbpqSavUAtebcIkDjSkL318bAfOrNnheQWhcAd/lKIgv3SCWQyYrRPv9BZjkpWpicxVdXbhLsixDx0a+eyrUGngyCP1353GbtTF6eDqko64DEQwg2c7PgEfj7TTJla3sMFmP8M/Pn6nn/cPwd69mRJYuV4bhfYsxBDh36Fwq5VVFlDK2jnNv+vSkqoya6kCgTEWn+UxIHZp4DtlTvC+C+8acTse9vwlpY37dwxL4povaJHwjMiwJjjBI146gv8707mDz48FUEGkOzFIl2uhOJFciNrhLd4v/ELlbztb0/Da0AQ3OtsDrAHkpEwIDAQABo4IBXTCCAVkwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBRdiFut62X7/mii5NlvPVdyou8rmTAwBggrBgEFBQcBAQQkMCIwIAYIKwYBBQUHMAGGFGh0dHA6Ly9vY3NwLmxsYW1hLnBlMCQGA1UdEQQdMBuBGW9maXBhcGVsX2VpcmxAaG90bWFpbC5jb20wRgYDVR0gBD8wPTA7Bg0rBgEEAYOXdwABAAIBMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8vbGxhbWEucGUvcmVwb3NpdG9yeS8wHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMDoGA1UdHwQzMDEwL6AtoCuGKWh0dHA6Ly9jcmwubGxhbWEucGUvbGxhbWFwZXN0YW5kYXJkY2EuY3JsMB0GA1UdDgQWBBSm3H1xB3ZPg04R/2kb9kn7QrpCBzAOBgNVHQ8BAf8EBAMCBsAwDQYJKoZIhvcNAQELBQADggEBACL4730kuy8qfLV50SrvQFfLA8UmYv8kvVt4X8bnx/CtJxc2/+rupfo6XwlogMcmehoImTuoMh8HLoUB2//mzKYexIoYqR6DBj9O8FFSfTr1ufDmpKr8ZQOa1ZeTehyRgwU+h4jc/Xfzec38Zru76x5B+QnEWWo1yQZio554K80kI+F9FORXtH+Tv74ous74iuKB7kqQitnHy7OEoQTovuKAOV4k5K+zhbdsMiaxaP3fTS+rRKZM4JtIaSOu/Z8bqJa2peP5mTDj2XcgW55l+6wXAAywakY1tl8Sx5WClVzWzIXqZ+levI65jFjehmdJnLb3WGB+ghK27PmF17HDR3U=
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</ds:Signature>
</ext:ExtensionContent>
</ext:UBLExtension>
</ext:UBLExtensions>
<cbc:UBLVersionID>2.0</cbc:UBLVersionID>
<cbc:CustomizationID>1.0</cbc:CustomizationID>
<cbc:ID>RA-20191019-001</cbc:ID>
<cbc:ReferenceDate>2019-10-16</cbc:ReferenceDate>
<cbc:IssueDate>2019-10-19</cbc:IssueDate>
<cac:Signature>
<cbc:ID>20532639680</cbc:ID>
<cbc:Note>GREENTER Builder</cbc:Note>
<cac:SignatoryParty>
<cac:PartyIdentification>
<cbc:ID>20532639680</cbc:ID>
</cac:PartyIdentification>
<cac:PartyName>
<cbc:Name>
<![CDATA[ OFIPAPEL E.I.R.L. ]]>
</cbc:Name>
</cac:PartyName>
</cac:SignatoryParty>
<cac:DigitalSignatureAttachment>
<cac:ExternalReference>
<cbc:URI>#SIGN-GREEN</cbc:URI>
</cac:ExternalReference>
</cac:DigitalSignatureAttachment>
</cac:Signature>
<cac:AccountingSupplierParty>
<cbc:CustomerAssignedAccountID>20532639680</cbc:CustomerAssignedAccountID>
<cbc:AdditionalAccountID>6</cbc:AdditionalAccountID>
<cac:Party>
<cac:PartyLegalEntity>
<cbc:RegistrationName>
<![CDATA[ OFIPAPEL E.I.R.L. ]]>
</cbc:RegistrationName>
</cac:PartyLegalEntity>
</cac:Party>
</cac:AccountingSupplierParty>
<sac:VoidedDocumentsLine>
<cbc:LineID>1</cbc:LineID>
<cbc:DocumentTypeCode>01</cbc:DocumentTypeCode>
<sac:DocumentSerialID>F001</sac:DocumentSerialID>
<sac:DocumentNumberID>00001181</sac:DocumentNumberID>
<sac:VoidReasonDescription>
<![CDATA[ ERROR DE DIGITACION ]]>
</sac:VoidReasonDescription>
</sac:VoidedDocumentsLine>
</VoidedDocuments>`

**Comment by JHONQUISPEFLORES** [comment]
[20532639680-RA-20191019-001.xml.pdf](https://github.com/giansalex/greenter-sample/files/3755303/20532639680-RA-20191019-001.xml.pdf)

**Comment by giansalex** [comment]
@JHONQUISPEFLORES llegue a validarlo pero no salio ningun problema, y viendo el contenido no encuentro algo que pueda estar mal.

**Comment by JHONQUISPEFLORES** [comment]
sabes en la factura 1181 que se quiere anular salio con una observación, no se si eso sea el motivo que no quiere anular (y lo peor de todo que todo empezó en una fecha de este mes, extrañamente, porque no sucedía antes el error): 
![image](https://user-images.githubusercontent.com/31812268/67540079-b9493780-f6a9-11e9-85f4-1dd533038aa3.png)
 pero te adjunto los xml, cdr de la factura origen
xml:
 https://drive.google.com/file/d/1MFurAMIAxKbnGJYRwZ-Gt8NzFWbgKUMo/view?usp=sharing
cdr:
https://drive.google.com/file/d/1bWOBMBL0zIewSciIMJ-wnqGHWIZApDKD/view?usp=sharing
pdf:
https://drive.google.com/file/d/1T9hK50SwzsDuB5fyXDTIk8oZQ59FrUsA/view?usp=sharing

pero en realidad no detecto el error

**Comment by giansalex** [comment]
si, realmente es muy extraño. No creo que tenga que ver con que la factura tenga observaciones, porque de todas formas esta aceptado, de lo contrario deberia devolver un mensaje indicando eso.

Por otro lado, el modelo de PDF que usas se ve compacto, probablemente tome algunas cosas para el modelo actual (seria util si compartieras los css, html que usaste 😄 )
