### ISSUE TITLE
observación icbper xml y pdf

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [giansalex/greenter-sample#76]
![obs](https://user-images.githubusercontent.com/31812268/72025982-f1432e00-3247-11ea-9037-61ae4bb76422.png)

uno es el que genera el xml y el otro la representación impresa pdf, deberia ser igual??

**Comment by giansalex** [comment]
Hola @JHONQUISPEFLORES, si deberian ser iguales. Ya lo corregí.
