### ISSUE TITLE
Como puedo realizar todo el proceso en dos partes

### ISSUE THREAD

**Issue by efrain2204** [giansalex/greenter-sample#79]
Buenos dias @giansalex , estoy usando tu ejemplo pero quiero en una primera etapa solo obtener el ticket (logrado), pero despues quiero obtener el cdr  cuando presione un boton.

**Comment by MrJmpl3** [comment]
Pues ejecutas una parte, guardas el ticket y ejecutas la otra parte despues

**Comment by efrain2204** [comment]
Con el ticket almacenado en la DB pude hacer la validación .Gracias
