### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by abelnexus** [giansalex/greenter-sample#9]
![captura](https://user-images.githubusercontent.com/34687414/35474669-93bdf2ec-035f-11e8-81e2-8d270a949026.PNG)

**Comment by abelnexus** [comment]
amigo tengo esas 2 tablas ventas y detalle-ventas en detalle_ventas estan los items de cada venta,
como meteria esos items en:
![captura](https://user-images.githubusercontent.com/34687414/35474701-df1b61b6-035f-11e8-8267-5ea93ccff2b1.PNG)

**Comment by abelnexus** [comment]
alguna sugerencia ?

**Comment by giansalex** [comment]
si usas pdo puedes hacerlo de esta forma.

```php
$invoice = new Invoice();

$items = [];
$result = $con->query("SELECT...");

while($row = $result->fetch(PDO::FETCH_ASSOC)) {
  $detail = new SaleDetail();
  $detail->setDescripcion($row["producto"])
         ->setCantidad($row["cantidad"]);
  // llenar los demas campos
   $items[] = $detail;
}
$invoice->setDetails($items);
```

**Comment by abelnexus** [comment]
lo estoy tratando de implementar, pero tengo un grave error :'( mi arquitectura es mvc Y poo y no puedo incluirle la carpeta "vendor/autoload.php" 
![captura](https://user-images.githubusercontent.com/34687414/35526542-c07202c8-04f5-11e8-8639-882a17b07334.PNG)

**Comment by giansalex** [comment]
si factu es la carpeta raiz de tu projecto seria algo asi.  
```php
include __DIR__.'/../../vendor/autoload.php';
```

**Comment by abelnexus** [comment]
si ya lo intente y no me deja, solo puedo incluirlo en las vistas

**Comment by giansalex** [comment]
el error indica que no puede abrir el autoload.php, tiene que ser problema de la ruta. Puedes colocar la ruta absoluta para verificar que si lo toma.

**Comment by abelnexus** [comment]
es un poco dificil de explicar 
pero estoy seguro que concoes esta arquitectura
![captura](https://user-images.githubusercontent.com/34687414/35539090-363dc9e2-051e-11e8-98eb-afdc82b16e3a.PNG)

**Comment by abelnexus** [comment]
este es el controlador

**Comment by abelnexus** [comment]
lo que intento hacer es pasarle tus librerias aca al controlador de ventas para ahi mismo crear la factura xml

**Comment by abelnexus** [comment]
pero cuando lo coloco este controlador deja de funcionar

**Comment by giansalex** [comment]
usas algún framework, parece codeigniter, si es ese puedes guiarte aqui
https://serprogramador.es/integrar-composer-a-codeigniter/

**Comment by abelnexus** [comment]
desgraciadamente no es codeigniter  :( es un framework reciclado

**Comment by abelnexus** [comment]
ya logre incluirlo :D

**Comment by abelnexus** [comment]
ahora me surge un problemilla mas :'v
![captura](https://user-images.githubusercontent.com/34687414/35573246-85c16880-05a4-11e8-9a1a-58daf27ebcda.PNG)

**Comment by abelnexus** [comment]
cuando uso un evento para abrir esa pagina y ahi le meto el codigo del reporte de factura sale eso D:

**Comment by giansalex** [comment]
eso con que lo generas.

**Comment by abelnexus** [comment]
<form action="<?=URL?>ventas/registrar" class="frm-ventas" method="post">
        <div class="col-xs-12 col-sm-12 col-md-8">
            <div id="caja" class="alert alert-danger" style="display:none;">

            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label class="col-xs-12 col-md-2 control-label" style="padding: 0;">
                            Producto
                        </label>
                        <div class="col-xs-12 col-md-10" style="padding: 0;">
                            <input type="text" id="producto" class="form-control" placeholder="Buscar por código de barra o nombre del producto" />
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12" id="carrito_ventas" style="padding-top: 30px">
                    <div class="cargando" style="text-align: center;display: none;">
                        <img src="<?=URL?>public/assets/images/loader.gif" alt="Cargando">
                        <p>Cargando Productos...</p>
                    </div>
                    <div class="table-scrollable" style="border: none;">
                        <table class="table table-carrito">
                            <thead class="bordered-blue">
                                <tr style="background: #d9edf7;">
                                    <td class="text-center">ITEM</td>
                                    <td class="text-center">CANT.</td>
                                    <td class="text-center">MEDIDA</th>  
                                    <td class="text-center">PRODUCTO</th>                               
                                    <td class="text-center">PRECIO</td>
                                    <td class="text-center">IMPORTE</td>
                               
                                 </tr>
                
                            </thead>
                        <tbody></tbody>
                               
                        </table>
                       
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center button">
                    <button type="submit" name="guardar" class="btn btn-info btn-flat">
                        <i class="glyphicon glyphicon-shopping-cart"></i> GUARDAR VENTA
                    </button>
                    <a href="javascript:void(0);" class="btn btn-danger btn-flat" url="<?=URL?>ventas/destroy">
                        <i class="glyphicon glyphicon-trash"></i> VACIAR CARRITO
                    </a>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="box-pago">
                        <div class="header bg-themeprimary">
                            <h4>TOTAL A PAGAR</h4>
                        </div>
                        <div class="body">
                            <h3>
                                <span><?php echo Validar::moneda(); ?> </span>
                                <span class="total"></span>
                            </h3>
                        </div>
                    </div>
                    <div class="box-pago">
                        <div class="header bg-themesecondary">
                            <h4>IMPORTE RECIBIDO</h4>
                        </div>
                        <div class="body">
                            <h3>
                                <span><?php echo Validar::moneda(); ?> </span>
                                <span class="recibido">0.00</span>
                            </h3>
                        </div>
                    </div>
                    <div class="box-pago">
                        <div class="header bg-darkorange">
                            <h4>CAMBIO</h4>
                        </div>
                        <div class="body">
                            <h3>
                                <span><?php echo Validar::moneda(); ?> </span>
                                <span class="cambio"></span>
                            </h3>
                        </div>
                    </div>
                </div>
        </div>
    </div>                              
           
              <div class="col-xs-12 col-sm-12 col-md-4">
            <div class="box services-box">
              
                <div class="box-body">
                    <div class="col-md-6" style="padding-bottom: 15px">
                        <label for="">COMPROBANTE</label>
                        <select required name="documento" id="documento" class="form-control">
                        </select>
                        <input type="hidden" name="Tipo_Doc" id="tipodoc" value="">
                    </div>
                    <div class="col-md-6" style="padding-bottom: 15px">
                        <label for="">TIPO MONEDA</label>
                        <select required name="pago" class="form-control" id="pago">
                            <option value="PEN" selected>SOLES</option>
                            <option value="USD">DOLARES</option>
                        </select>
                    </div>
                    <div class="col-md-6 disabled">
                        <label for="">SERIE</label>
                        <input type="text" name="serie" id="serie" class="form-control" autocomplete="off" required readonly placeholder="F001" ="">
                    </div>
                    <div class="col-md-6 disabled">
                        <label for="">N° CORRELATIVO</label>
                        <input type="number" name="numero" id="numero" class="form-control" autocomplete="off" readonly required placeholder="000001"="">
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12" style="padding-top: 15px">
                        <label for="">CLIENTE</label>
                        <input type="text" id="cliente" name="cliente" class="form-control" required placeholder="Ruc o Razón Social"></input>
                        <input type="hidden" id="codigo" name="codigoCliente" value="">
                        <input type="hidden" id="direccion" name="direccion" value="">
                        <input type="hidden" id="ruc" name="ruc" value="">
                        <input type="hidden" id="total" name="total" value="">
                    </div>
              
                
                    <div class="col-xs-12 col-sm-12 col-md-12" style="padding-top: 15px">
                        <div class="border"></div>
                        <table width="100%">
                            <tr>
                                <td>SUB TOTAL</td>
                                <td class="text-center"><?php echo Validar::moneda(); ?>
                                    <span class="subtotal">0.00</span>
                                </td>
                            </tr>
                            <tr>
                                <td>I.G.V (<?=Validar::igv()?>%)</td>
                                <td class="text-center"><?php echo Validar::moneda(); ?>
                                    <span class="igv">0.00</span>
                                </td>
                            </tr>
                            <tr>
                                <td>TOTAL</td>
                                <td class="text-center"><?php echo Validar::moneda(); ?>
                                    <span class="total">0.00</span>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
      </form>

**Comment by abelnexus** [comment]
todo ese formulario al momentor de darle submit
![captura](https://user-images.githubusercontent.com/34687414/35573696-d2d28efa-05a5-11e8-9a0d-099eaca06833.PNG)

**Comment by abelnexus** [comment]
y esa funcion es imprimir ticket
![captura](https://user-images.githubusercontent.com/34687414/35573778-011324c8-05a6-11e8-8746-cfb89fb895fa.PNG)

**Comment by abelnexus** [comment]
lo que hace eso es abrirme esta pagina 
![captura](https://user-images.githubusercontent.com/34687414/35573831-25758b62-05a6-11e8-955a-08fcb7f27808.PNG)

**Comment by abelnexus** [comment]
y en esa pagina pongo el codigo del reporte
![captura](https://user-images.githubusercontent.com/34687414/35573861-40230156-05a6-11e8-84de-afc48d959f93.PNG)

**Comment by abelnexus** [comment]
enviandole el codigo de ultima venta registrada de hecho todo ocurre al recibir por mensaje la confirmacion que se ingreso correctamente en la bd y me captura el codigo de ultima venta y eso lo envia al print_ticket.php para sacar los datos desde ese codigo
![captura](https://user-images.githubusercontent.com/34687414/35573968-928a7280-05a6-11e8-8006-ab806f087da0.PNG)

**Comment by abelnexus** [comment]
para hacer este sistema estoy reciclando otros 2 sistemas de uno su framework y del otro sus stylos
te enviare a tu correo ese sistema

**Comment by giansalex** [comment]
tal vez no has colocado los headers adecuados, por ejemplo si es pdf.
```php
header("Content-type: application/pdf");
header("Content-Disposition: inline;filename='downloaded.pdf'");

echo $contentPdf;
```

**Comment by abelnexus** [comment]
ya te envie a tu correo

**Comment by giansalex** [comment]
lo único que me llego fue 
`la contraseña de del usuario es 123456 `

**Comment by abelnexus** [comment]
![captura](https://user-images.githubusercontent.com/34687414/35575610-ca58b95c-05aa-11e8-939b-a8277cb4ae5c.PNG)

**Comment by abelnexus** [comment]
te volvi a enviar

**Comment by giansalex** [comment]
lo siento, no me llego ningun adjunto.
![image](https://user-images.githubusercontent.com/14926587/35575835-6b6e2e12-05ab-11e8-895d-15a13aa217bb.png)

**Comment by abelnexus** [comment]
https://drive.google.com/file/d/1R4A8QcaOcmMBL6odnT7BweO4I0GDvxMP/view

**Comment by abelnexus** [comment]
ahora se pudo ?

**Comment by abelnexus** [comment]
https://www.4shared.com/s/fI7lugHJIei

**Comment by abelnexus** [comment]
amigo estas ?

**Comment by giansalex** [comment]
he podido abrir el archivo, pero son varias configuraciones que se tiene que realizar para poderlo probar, ahora mismo no cuento con el tiempo. Primero debes probar generando el pdf y guardandolo en el servidor, luego fijate en el content-type envias, parece que mostraras 2 resultados (la respuesta de sunat y el pdf) en una mismo request.

**Comment by abelnexus** [comment]
de alguna manera ya me salio pero no como deseo:
    public function generar_factura($data)
	{
		   $see = Util::getSee(SunatEndpoints::FE_BETA);
           $res = $see->send($data);
          Util::writeXml($data, $see->getFactory()->getLastXml());
          if ($res->isSuccess()) {
          $cdr = $res->getCdrResponse();
          Util::writeCdr($data, $res->getCdrZip());
          $this->sms = 'aceptado por sunat';
          Util::getResponseFromCdr($cdr);          
    
            } else {
               var_dump($res->getError());
          } 
		return $this->sms;
	}

**Comment by abelnexus** [comment]
solo recibo ese mensaje de "aceptado por sunat" :'''v 
pero yo quiero que me diga la "La Factura numero F001-123, ha sido aceptada"

**Comment by giansalex** [comment]
puedes obtenerlo del cdr, 
```php
//...
$cdr = $res->getCdrResponse();
Util::writeCdr($data, $res->getCdrZip());
$this->sms = $cdr->getDescription(); // La Factura ... ha sido aceptada.

```

**Comment by abelnexus** [comment]
ya lo consegui muchas gracias :D
